apiVersion: v1
kind: Secret
metadata:
    name: shlink-backend-secret
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:rqWMkfwuRhM8AbQbwwAfav1SGYYB9BtBmK9Vm5Wl3n5Dwyx/kn7Sxd7l2jKuF43SUNbWQl4LipVieDKZRmBvag==,iv:uS7oE9iLAzkWyewjyZuKsUhCz+ZgrVkTrouIys+8/zY=,tag:wx3LPPewcQ2oM+AZyP4VOQ==,type:str]
    geoip-license-key: ENC[AES256_GCM,data:irpeb+e9wkIyzJh9cfNKwW74KC3LApiMVb/VDltzLagz5BWSwO3/JQ==,iv:1G1aEMqV6Vbxw0d54ezQw51v7YIUM8i7CfYxDIYBhCs=,tag:Q/uTqCY18JB0h5wduvRmYg==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRmlxRThqTmpCNzZFT1JY
            Y0N5cDJOQVl6clVoRFpGTEVPWFA0bXZqM2hNClQyNEt3cWFmMXVMcjFsNzIyU1E0
            RHI0cThXZDdqdlNESmQ3K2RyOXFRckEKLS0tIFdwOVpoRnlQZ0lmUkRhTmxTOGhO
            elNvcWNTbzEwTHM5c2hrQUdqbDNhMU0KVPidoP3/Gu+KPGMh3Q/1J7BvP3gEO82d
            dkJxEExd3g4cG+AZGHGkvL/uVEy6M4nXvNX1HfDUTzohQf6/IZJHgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T19:12:08Z"
    mac: ENC[AES256_GCM,data:wQn2UW7AV3gJWKj53RMsjwK4Kp6znLPp/iDkusoO2ZyzTKLmQ4HHmc2o5reWk6Nks9X58jtzcnHlkfsit60O78bL7sBku28lHj5BWwAUnqwHsobeyPhdzOVmNZS6bA3hc2FQA863AbIYh3tlmTbMY0d30pSFgb3+wwo20Vzk1Z4=,iv:13ipkzqUDl5jBXOsA5HAr/kq93djUa6Si0f89+kC/Kw=,tag:xxDpgbAlTh2g/ihJDgCGwQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
