apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: tempo
  name: tempo-kafka
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo
