# Source: tempo-distributed/templates/kafka/kafka-svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-kafka-headless
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: kafka
    prometheus.io/service-monitor: "false"
spec:
  type: ClusterIP
  # The headless service is used by Kafka brokers for discovering other brokers
  # during bootstrap. Thus, we don't want to require that they are "ready" to
  # publish their address - the brokers need to know about each other to become
  # ready.
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 9092
      protocol: TCP
      name: kafka
      targetPort: kafka
    - port: 9093
      protocol: TCP
      name: controller
      targetPort: controller
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: kafka
---
# Source: tempo-distributed/templates/kafka/kafka-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-kafka
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
    - port: 7071
      targetPort: http-metrics
      name: http-metrics
    - port: 9092
      protocol: TCP
      name: kafka
      targetPort: kafka
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: kafka
