namespace: kube-state-metrics
resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  # Removing this because cilium actually uses it and we want network from otel and thanos and elsewhere. Probably delete to be concise in the future.
  # - networkpolicy.yaml
  - prometheusrule.yaml
  - service.yaml
  - serviceaccount.yaml
  # Disable servicemonitor now so that the selfmetrics collector can scrape this pod explicitly
  # and the core-prometheus collector doesnt also scrape it.
  # - servicemonitor.yaml
