apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 3               # 3 dual-role nodes for a small HA cluster
  roles:
  - controller
  - broker
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 100Gi
      class: longhorn-kafka
      deleteClaim: true
      kraftMetadata: shared
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  strimzi.io/pool-name: dual-role
              topologyKey: kubernetes.io/hostname
    persistentVolumeClaim:
      metadata:
        labels:
          recurring-job.longhorn.io/source: "enabled"
          recurring-job-group.longhorn.io/kafka-trim: "enabled"
