apiVersion: v1
kind: Secret
metadata:
    name: homepage-env
type: Opaque
stringData:
    HOMEPAGE_VAR_MINIFLUX_API_KEY: ENC[AES256_GCM,data:qQT3DJTP7UlJHni5KPPC6n4M20ntvInlXv4nYccy6T6prWFRvKThWBXe2sPzu8k4iD7jKgIoLC45gfPzWpRvoQ==,iv:CTF+uk3fLVRjP4ceMPRv6QKiHuZvMv1Dq8vVS8i0e8U=,tag:E+HIA3ndP8nnjzLj84rkRw==,type:str]
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:OUtQna1xTs8jKHPGlq9FCY0JM4GT4yvuHGJeb46I66Y=,iv:5M4mMP2wGDTOKsD6fqt5yr/6fawuPNp2barE+etjffY=,tag:bN4+wKEg8+nexta/i0sA4w==,type:str]
    HOMEPAGE_VAR_ARGOCD_API_KEY: ENC[AES256_GCM,data:lkzKRBw+jx1LAE5nblOvPTTzYsBAItGHY3d87y4v5eNLlYWP6wPFMMaRmT1707iE/NX3PNi+KeoUfF08rQ8HGQ1q1VlO4wDltXrHdCW2skDkwfkEOiFIKus3x3xEMESz6VrAbzulfRPrkBwOGAQLy/Y9hl7mc8afNO8o9nzuJsRj+rZuXGzyWVIvVjaNS/MhBD2/fJOIlOVEarF6HkbQdF5sQ17ctwQh+sKV02nilkP1uE7shynIKg7JunFb9kiI4nDVuAfe5RpEQXQlMKowNrq8yz5IbBIkedWEBZ2Kx0/y+D9+O4wzhK63MMnJDCdU,iv:LAhq6G4RgwHp4rGP6MH9QDVP9LAzpIIB47w/wD+e5f0=,tag:fi60TxMdn5tckf5lygQZdA==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:se6Yb0kOI6oXFQ==,iv:7Q22mYqtQW4yk5uBjSXuxTxEKGAgLtbEFKkCDcp0g80=,tag:0fj6RzxY81CghsNlK6qaIQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:M3tVIH0dhkJkOx2GJIkiWQ==,iv:WyyxEJqHwTHRi8oHddNb5wPjmxtDTSXqVbkRH0Z+uZw=,tag:APpEm+cLzf+Hd9yDl+6ouA==,type:str]
    HOMEPAGE_VAR_FORGEJO_API_KEY: ENC[AES256_GCM,data:COFNO6Ys8IX1vl6tyjMoeBD/YdW7fwoAN5l5uJdjgcag3xD45uvIew==,iv:B6UjkUhUX9gUD6DU+Vo19Hx33VoOldaApjEspNol+wA=,tag:2zLjHU1fvz9DMElV6iFLFA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eFVObE5WbEFlcDhoMTdE
            UG52Ri9RL2ZXN2M4VDN3NGlINU5aMjBNcEU4CkJOVUUzcUZrTU9xaDZTeVJneDlu
            dVZ3Q2N3dnd3cW93akJIVVAxdFhZejgKLS0tIGpDSzh6SHZIM1B3bUh0WDhYdVNH
            aXdXajRoNDNrTk8wUTJDRXdTb2JPa2cKI46SlSl0xlGaiUZlNstFKCbbRcq6QQzC
            ce2bLdyV+5lSSPlzkZw9RshR6lXVfjZFfkdBzhv34sB/arO2gNt3Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T17:23:30Z"
    mac: ENC[AES256_GCM,data:pj/bqn4TgHaP0ESz7VxFfaiA8jIgHUeSZQ0nYE5g0cmtPagiv17No02hmkJecPftbc3m6fvyRN+ruE1hfGRK6Fnqgu1E5OjNBCumXzc+uyPzMQyX4IpzyOpZ+4zvmvzS2/Zbi/MvF+YyJrEshlzcJJUjJk77frcRfbkJLhtCny4=,iv:ME31SU4NWzDrR26t3HEV6F3HfgGx/2LIT1U/HzqWCxk=,tag:auqiDcyFjoKjuqzqlHQOeA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
    name: homepage
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        kubernetes.io/service-account.name: homepage
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eFVObE5WbEFlcDhoMTdE
            UG52Ri9RL2ZXN2M4VDN3NGlINU5aMjBNcEU4CkJOVUUzcUZrTU9xaDZTeVJneDlu
            dVZ3Q2N3dnd3cW93akJIVVAxdFhZejgKLS0tIGpDSzh6SHZIM1B3bUh0WDhYdVNH
            aXdXajRoNDNrTk8wUTJDRXdTb2JPa2cKI46SlSl0xlGaiUZlNstFKCbbRcq6QQzC
            ce2bLdyV+5lSSPlzkZw9RshR6lXVfjZFfkdBzhv34sB/arO2gNt3Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T17:23:30Z"
    mac: ENC[AES256_GCM,data:pj/bqn4TgHaP0ESz7VxFfaiA8jIgHUeSZQ0nYE5g0cmtPagiv17No02hmkJecPftbc3m6fvyRN+ruE1hfGRK6Fnqgu1E5OjNBCumXzc+uyPzMQyX4IpzyOpZ+4zvmvzS2/Zbi/MvF+YyJrEshlzcJJUjJk77frcRfbkJLhtCny4=,iv:ME31SU4NWzDrR26t3HEV6F3HfgGx/2LIT1U/HzqWCxk=,tag:auqiDcyFjoKjuqzqlHQOeA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
