#ENC[AES256_GCM,data:5GxIzDynHukr+VSZXOfyp5aGPEtijl0kJdQxC4aOQWlMH7mA32nj,iv:l7dQQLZ4qC3KgKjWXKy4SAg8aPiV9y8I3AErbxu9LoM=,tag:3DmVkZ4iklJ20wsp/WtzTA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: kube-system
type: Opaque
data: null
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z2pDV2NsVGlHd2hxL0pN
            c2txSWRkRjRKZHVDL0F0RlpuQW5iSzlRUlV3CkV1V25WQ2tuZzZiaWpnejZhMmdm
            WmdTM2IzZ3JKT1NXREtIZEhTSGVMUEEKLS0tIDlHVEM2S1JQUFZiUitNV0pjbmhG
            RStvLzV3RFpXRVVDMHdCcGpnRTdIU1UK7ynl7XXfkWokT1sJbAOrCj+P6RYj4XdP
            lUC4uGYbbR+EBKdsi1ZZNu3xF6GQQnV6bBAIKcQeOUbWEOGM/naFKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:12:03Z"
    mac: ENC[AES256_GCM,data:bAe+z6Wuy5+RQLx4mJNYPuUwtRb6fDVSPfQvzOaeAIvq1VIOtqWisiktvdeav3qnDHBWu7ICKAv+Z+hqEApSkRTBGZpiTKIfVUDrxVpYyJBqYQAR3cAmcYR8empcSpa0lYQrdjUU6abetoLKPqilx+CJWjeKvLTTuT1C/w+sT5s=,iv:ik1dwtXOQaTF9gIPWv52DOjynuQbc+V+uKGVdLMJscQ=,tag:OPTBExFOAtLflfgHLuaoYA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
