{
 "title": "External Secrets",
 "description": "Prometheus metrics for External Secrets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_active_workers,job)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{job=~\"$job\"},controller)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(externalsecret_sync_calls_total{job=~\"$job\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$controller controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "controller" },
  {
   "title": "Active Workers $controller",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=~\"$job\", controller=~\"$controller\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Max Concurrent Reconciles $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles{job=~\"$job\", controller=~\"$controller\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller, result) (rate(controller_runtime_reconcile_total{job=~\"$job\", controller=~\"$controller\"}[2m]))",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Errors Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (rate(controller_runtime_reconcile_errors_total{job=~\"$job\", controller=~\"$controller\"}[2m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Runtime Recincile Time $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99% - {{controller}}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95% - {{controller}}"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90% - {{controller}}"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, controller)(\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n        job=~\"$job\",\n        controller=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50% - {{controller}}"
    }
   ]
  },
  { "title": "$controller workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 }, "repeat": "controller" },
  {
   "title": "Depth $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "workqueue_depth{job=~\"$job\", name=~\"$controller\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Adds Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(workqueue_adds_total{job=~\"$job\", name=~\"$controller\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Longest Running Processor $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{job=~\"$job\", name=~\"$controller\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Retries Rate $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(workqueue_retries_total{job=~\"$job\", name=~\"$controller\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unfinished Work $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{job=~\"$job\", name=~\"$controller\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Duration $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, name)(\n    rate(\n      workqueue_work_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50% - {{name}}"
    }
   ]
  },
  {
   "title": "Queue Duration $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "99% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "95% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "90% - {{name}}"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, name)(\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n        job=~\"$job\",\n        name=~\"$controller\",\n      }[2m]\n    )\n  )\n)",
     "legendFormat": "50% - {{name}}"
    }
   ]
  },
  { "title": "$name external secret", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 540 }, "repeat": "name" },
  {
   "title": "Sync Calls Rate $name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 541 },
   "targets": [
    {
     "expr": "sum by (name, exported_namespace) (rate(externalsecret_sync_calls_total{job=~\"$job\", name=~\"$name\"}[2m]))",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Sync Calls Error Rate $name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 541 },
   "targets": [
    {
     "expr": "sum by (name, exported_namespace) (rate(externalsecret_sync_calls_error{job=~\"$job\", name=~\"$name\"}[2m]))",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration $controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 541 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "externalsecret_reconcile_duration{job=~\"$job\", name=~\"$name\"}",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Status $name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 541 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "externalsecret_status_condition{job=~\"$job\", name=~\"$name\", condition=\"Ready\", status=\"True\"}",
     "legendFormat": "{{name}} {{exported_namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "External Secrets Operator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{service=~\".*external-secrets.*\"},  controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SecretStore error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"secretstore\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"secretstore\"}[15m])))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ClusterSecretStore error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clustersecretstore\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clustersecretstore\"}[15m])))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ExternalSecret error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"externalsecret\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"externalsecret\"}[15m])))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ClusterExternalSecret error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clusterexternalsecret\", result=\"error\"}[15m])))\n/\n(sum(irate(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"clusterexternalsecret\"}[15m])))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PushSecret error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"pushsecret\", result=\"error\"}[15m])))\n/\n(sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"pushsecret\"}[15m])))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\", status=\"error\"}[15m]))\n/\nsum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\"}[15m]))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  workqueue_depth{service=~\"external-secrets.*\"}\n) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook error rate [15m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\"external-secrets.*\",code=\"500\"}[15m]))\n/\nsum(increase(controller_runtime_webhook_requests_total{service=~\"external-secrets.*\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook latency [5m]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(controller_runtime_webhook_latency_seconds_bucket{service=~\"external-secrets.*\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile latency [p99]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(controller_runtime_reconcile_time_seconds_bucket{service=~\"external-secrets.*\"}[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reconcile error rate [p99]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{service=~\"external-secrets.*\",controller=~\"$controller\",result=\"error\"}[1m]))\n/\nsum(increase(controller_runtime_reconcile_total{service=~\"external-secrets.*\",controller=~\"$controller\"}[1m]))\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider errors [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\", status=\"error\"}[15m])",
     "legendFormat": "{{provider}}/{{call}}"
    }
   ]
  },
  {
   "title": "Not Ready ExternalSecrets  [15m]",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(externalsecret_status_condition{condition=\"Ready\",status=\"False\"}) by (namespace, name) == 1",
     "legendFormat": "{{provider}}/{{call}}"
    }
   ]
  },
  {
   "title": "ExternalSecret sync call errors [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(externalsecret_sync_calls_error[15m])) by (name, namespace)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Admission Control Webhook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests by path per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\".*external-secrets.*\"}[1m])) by (webhook)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "requests in flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum(controller_runtime_webhook_requests_in_flight{service=~\".*external-secrets.*\"}) by (webhook)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "requests by code per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_webhook_requests_total{service=~\".*external-secrets.*\"}[1m])) by (code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "webhook latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_webhook_latency_seconds_bucket{service=~\".*external-secrets.*\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "active workers by controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(controller_runtime_active_workers{service=~\".*external-secrets.*\",controller=~\"$controller\"}) by (controller)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "workqueue depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 17 },
     "targets": [
      {
       "expr": "sum(workqueue_depth{service=~\".*external-secrets.*\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API calls by provider",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
     "targets": [
      {
       "expr": "sum(increase(externalsecret_provider_api_calls_count{service=~\".*external-secrets.*\"}[1m])) by(provider, call, status)",
       "legendFormat": "{{provider}}/{{call}}={{status}}"
      }
     ]
    },
    {
     "title": "max concurrent: $controller",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 0, "y": 25 },
     "repeat": "controller",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(controller_runtime_max_concurrent_reconciles{service=~\".*external-secrets.*\",controller=\"$controller\"}) by (controller)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "reconcile rate per minute: $controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 31 },
     "repeat": "controller",
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_reconcile_total{service=~\".*external-secrets.*\",controller=~\"$controller\"}[1m])) by (result)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "reconcile time latency: $controller",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 39 },
     "repeat": "controller",
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{service=~\".*external-secrets.*\",controller=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}