{
 "title": "Jellyfin Native Prometheus Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"jellyfin\"}",
     "legendFormat": "Dotnet total memory"
    },
    {
     "expr": "process_private_memory_bytes{job=\"jellyfin\"}",
     "legendFormat": "Process private memory"
    },
    {
     "expr": "process_working_set_bytes{job=\"jellyfin\"}",
     "legendFormat": "Process working set"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{job=\"jellyfin\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{controller}} {{action}} {{code}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(dotnet_exceptions_total{job=\"jellyfin\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}
{
 "title": "Jellyfin Exporter",
 "tags": [ "jellyfin" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,30s,1m,5m,10m,30m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jellyfin_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_media_count{type=\"Movie\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_media_count{type=\"BoxSet\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_media_count{type=\"Series\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TV Show Episodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_media_count{type=\"Episode\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Now Playing - Movies",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (username, item_index_clean, type) (label_replace(label_join(label_join(jellyfin_now_playing{instance=~\"$instance\"}, \"item_index\", \" \", \"series_season\",  \"series_episode\"), \"full_name\", \" - \", \"series_title\", \"item_index\", \"title\"), \"item_index_clean\", \"$1\", \"full_name\", \"^[- ]*(.*?)[- ]*$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Now Playing - TV Shows",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (username, item_index_clean, type) (label_replace(label_join(label_join(jellyfin_now_playing{instance=~\"$instance\"}, \"item_index\", \" \", \"series_season\",  \"series_episode\"), \"full_name\", \" - \", \"series_title\", \"item_index\", \"title\"), \"item_index_clean\", \"$1\", \"full_name\", \"^[- ]*(.*?)[- ]*$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(jellyfin_user_active{instance=~\"$instance\"}) by (username, client, device, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "jellyfin_activity_count{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "I/O Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_fs_reads_bytes_total{container=\"jellyfin\"}[$interval]) or irate(container_fs_reads_bytes_total{container=\"jellyfin\"}[5m])",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_fs_writes_bytes_total{container=\"jellyfin\"}[$interval]) or irate(container_fs_writes_bytes_total{container=\"jellyfin\"}[5m])",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "container_memory_usage_bytes{container=\"jellyfin\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "container_spec_memory_limit_bytes{container=\"jellyfin\"} - container_memory_usage_bytes{container=\"jellyfin\"}",
     "legendFormat": "Available"
    },
    {
     "calculatedInterval": "2s",
     "expr": "container_memory_cache{container=\"jellyfin\"}",
     "legendFormat": "Cache"
    },
    {
     "calculatedInterval": "2s",
     "expr": "container_memory_mapped_file{container=\"jellyfin\"}",
     "legendFormat": "Mapped Files"
    }
   ]
  },
  {
   "title": "CPU Usage / Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_cpu_usage_seconds_total{container=\"jellyfin\"}[$interval]) * 100 or irate(container_cpu_usage_seconds_total{container=\"jellyfin\"}[5m]) * 100",
     "legendFormat": "Jellyfin CPU %"
    }
   ]
  },
  {
   "title": "Jellyfin I/O Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops/sec" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(container_fs_reads_total{container=\"jellyfin\"}[$interval]) or irate(container_fs_reads_total{container=\"jellyfin\"}[5m])",
     "legendFormat": "Read Ops"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(container_fs_writes_total{container=\"jellyfin\"}[$interval]) or irate(container_fs_writes_total{container=\"jellyfin\"}[5m])",
     "legendFormat": "Write Ops"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_network_transmit_bytes_total{pod=\"jellyfin-0\"}[$interval]) or irate(container_network_transmit_bytes_total{pod=\"jellyfin-0\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(container_network_receive_bytes_total{pod=\"jellyfin-0\"}[$interval]) or irate(container_network_receive_bytes_total{pod=\"jellyfin-0\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Jellyfin Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "container_memory_swap{container=\"jellyfin\"}",
     "legendFormat": "Swap Usage"
    },
    {
     "calculatedInterval": "2s",
     "expr": "container_memory_working_set_bytes{container=\"jellyfin\"}",
     "legendFormat": "Working Set"
    }
   ]
  }
 ]
}