{
 "title": "Grafana Loki Dashboard for Istio Service Mesh",
 "description": "Parsing Envoy access logs with Grafana Loki",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label name", "query": "label_names()" },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}\n| pattern `<_> \"<method> <path> <protocol>\" <status_code> <response_flags> <response_code_details> <connection_termination_details> \"<failure_reason>\" <bytes_received> <bytes_sent> <duration> <upstream_time> \"<forward_for>\" \"<agent>\" \"<req_id>\" \"<authority>\" \"<upstream_host>\" <upstream_cluster> <upstream_local_address> <downstream_local_address> <downstream_remote_address> <requested_server_name> <route_name>`\n| line_format \"{{ .method }} request to {{ .path }} with HTTP status: {{.status_code }}\""
    }
   ]
  },
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}[$__range]))  ",
     "legendFormat": "{{server_address}}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (http_response_status_code) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} \n | __error__=\"\"\n | http_response_status_code =~\"0|2..|3..|4..|5..\" \n[$__interval])) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Istio logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(bytes_over_time({category=\"access\", service_name=~\"$service_name\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Total Request Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(sum_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}\n| pattern `<downstream_ip> - - [<timestamp>] \"<method> <path> <protocol>\" <status_code> <bytes_sent> <bytes_received>`\n| unwrap bytes_received\n|  __error__=\"\"\n[$__range]))",
     "legendFormat": "{{bytes_sent}}"
    }
   ]
  },
  {
   "title": "Total Response Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(sum_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}\n| pattern `<downstream_ip> - - [<timestamp>] \"<method> <path> <protocol>\" <status_code> <bytes_sent> <bytes_received>`\n| unwrap bytes_sent\n|  __error__=\"\"\n[$__range]))",
     "legendFormat": "{{bytes_sent}}"
    }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count (sum by (downstream_remote_address) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}\n[$__range])))"
    }
   ]
  },
  {
   "title": "# Istio log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} | pattern `<_> \"<method> <path> <protocol>\" <status_code> <response_flags> <response_code_details> <connection_termination_details> \"<failure_reason>\" <bytes_received> <bytes_sent> <duration> <upstream_time> \"<forward_for>\" \"<agent>\" \"<req_id>\" \"<authority>\" \"<upstream_host>\" <upstream_cluster> <upstream_local_address> <downstream_local_address> <downstream_remote_address> <requested_server_name> <route_name>` \n| status_code >= 500 |__error__=\"\" [$__interval]))\n/\n(sum(count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} | pattern `<_> \"<method> <path> <protocol>\" <status_code> <response_flags> <response_code_details> <connection_termination_details> \"<failure_reason>\" <bytes_received> <bytes_sent> <duration> <upstream_time> \"<forward_for>\" \"<agent>\" \"<req_id>\" \"<authority>\" \"<upstream_host>\" <upstream_cluster> <upstream_local_address> <downstream_local_address> <downstream_remote_address> <requested_server_name> <route_name>` \n| __error__=\"\" [$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by bots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} |~ \"Googlebot|Slack.+\")[$__interval])) / (sum(count_over_time(({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} !~ \"Googlebot|Slack.+\")[$__interval])) / 100)"
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "95th percentile of duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.95,\n  {\n    $label_name=~\"$label_value\", \n    service_name=~\"$service_name\", \n    instance=~\"$instance\"\n  } \n  | unwrap http_request_duration\n  | __error__=\"\"  \n  [$__interval]\n) \nby (service_name, url_path)",
     "legendFormat": "{{service_name}} {{url_path}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (service_name, url_path) (max_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}\n| unwrap http_request_duration \n|  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{service_name}} {{url_path}}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (http_response_status_code) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} \n | __error__=\"\"\n | http_response_status_code =~\"0|2..|3..|4..|5..\" \n[$__interval])) ",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "timeseries",
   "description": "HTTP Request Size",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server_address) (sum_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} | http_response_status_code=200 | unwrap http_request_size |  __error__=\"\" [$__range]))",
     "legendFormat": "{{server_address}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "description": "HTTP Response Size",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server_address, service_name) (sum_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} | http_response_status_code=200 | unwrap http_response_size |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{server_address}} {{service_name}}"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Top 10 paths by duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(20,\n  max_over_time({\n    $label_name=~\"$label_value\", \n    service_name=~\"$service_name\", \n    instance=~\"$instance\"\n  } \n  !~ `.ico|.svg|.css|.png|.txt|.js|.xml`\n  | unwrap http_request_duration \n  | __error__=\"\" \n  [$__range]) \n  by (url_path, service_name)\n)",
     "legendFormat": "{{url_path}} "
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (http_request_header_x_forwarded_for) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} |  __error__=\"\" [$__range])))",
     "legendFormat": "{{http_request_header_x_forwarded_for}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Services",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (service_name) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} \n!~ `.ico|.svg|.css|.png|.txt|.js|.xml`\n| __error__=\"\" [$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (service_name, url_path) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"} \n!~ `.ico|.svg|.css|.png|.txt|.js|.xml`\n| __error__=\"\" [$__range])))",
     "legendFormat": "{{url_path}} {{service_name}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (user_agent_original) (count_over_time({$label_name=~\"$label_value\", service_name=~\"$service_name\", instance=~\"$instance\"}\n| __error__=\"\" [$__range])))",
     "legendFormat": "{{user_agent_original}}"
    }
   ]
  }
 ]
}