namespace: loki
resources:
  - namespace.yaml
  - memcached
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  # - httproute.yaml
  # - virtualservice.yaml
  - service.yaml
  # 2026-03-20 switching to per-service servicemonitors like we have for mimir and tempo for proper mixin dashboard rendering
  # - servicemonitor.yaml
  # - podmonitor.yaml
  - prometheusrule.yaml
  - grafanadatasource.yaml
  - dashboards
  # - metrics-grafanadashboard.yaml
  - probe.yaml
  - compactor
  - distributor
  - gateway
  - index-gateway
  - ingester
  - pattern-ingester
  - querier
  - query-frontend
  - query-scheduler
  - ruler

configMapGenerator:
- files:
  - files/loki.yaml
  name: loki
  options:
    immutable: true
