apiVersion: v1
kind: Secret
metadata:
    name: mimir-objectstorage
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:et5L0vA=,iv:F/AcYTUuvX+I7KwrARVYXshbC3HZzGhi+jzSsD21G18=,tag:9sOObAaVA1wpswG01m15pA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:b81TftMk86E1Tw==,iv:UsQ/4FOv8ZbU4HlqmBtbBARxBoJcwMrAEKt8CPIQ9U8=,tag:Iv3GoXL1ZxOb620R9nTaDQ==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN1NNYXBEUk1tY2dnUjBr
            TjVqa3dSY1lxdmdUVnR6cmFDZnFpeVJjVncwCkNyUXNOeG8zR2taQTIyUGhWZUto
            UGpIbFlUUks2YWR2UCtPRUd2eTNnQTgKLS0tIE1JbWVoUXl3NklyVXp2TkEzWm45
            N3NJUld5TjVrNFFQK1BtQjA1RCs4bXMKkK6KxD+hXgJRlJbstlJyIuRhRofLbE6B
            pzU8+wRE0FNx0hXnqi/L19gIJoBWI8VSSTGOVYtPezQAFBuPmzYvsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T19:58:01Z"
    mac: ENC[AES256_GCM,data:8Neb7gd15aLrlBH/Etd6AXQLAHU3mNd4HTDeEQ15+LUcym+1886HhP758uRwPwAHp9ktsHo8TgOqqYzoD1IwanD6dxsnJFMropt/hiMdyvW+0A6E5rrw0Zif1ck4rXmonkA7x+FwMsm/9cxLtQtMfn6gJC5wDSfA0NlLq4+MOOo=,iv:Zz+46lsTHATVnkqQi/4enb0jbOXqlVqno3PRNiIu/Z8=,tag:JyeuOQSxKOg5onT+rUeJ2A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
