apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: 2fauth-config
  name: 2fauth-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
