kind: Secret
apiVersion: v1
metadata:
    name: 2fauth-secret
stringData:
    app-key: ENC[AES256_GCM,data:8z5w+HcGEIMLsxw6o8frgeMwIsy2T2ro3fnrC4ZA32M=,iv:0n1HrzclTjSY07Ua/308/ecYVS5JFAjILYFamO/rTpc=,tag:W8Gyx4XOSuCGXenIdibSAg==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdk5pSnhKUjc1NUhrNU9F
            dzlPZzVXNjk2ZUE4Z0hRNE9OZFo2WDBSQkVvClovZFhVbEZsWEtzc2RIZlhkbGFO
            Wi93ZGZ3M1BGSXN0ZFRGRlk1aEhmTTgKLS0tIENveGNUTktaT0FlSEVkcklNMytI
            QUlTd2xXZ01uNUM4djBWdnNWVitBRG8K+WhJlRig153yCz570CDCKjnlyxzTt7U8
            T/x7YNaKt3GDO4dL+OEVjRv+jv9b2KQGBxIwdUBkzpCyxpMN1m4lBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T02:11:50Z"
    mac: ENC[AES256_GCM,data:bsCHU8WTu0LsX73f9fHcoNVilHucw2wCzfxArs1lqXkZ7X8I9aTEhxVNJzyWAoMyZPV+lLkGbWnRoLkVvRbGznvrCVfTkYwd8bFKwAxOXVSebCFHvuk0UrVl7ZYpTh06YX1L5PFll9aOvCkQCJ2sKZ2DcPLKB2r+eyer9FgrWgE=,iv:OeaFQxNMmDnhYSoFoVG2JE7l3urQVXpq5D4REnJZWKs=,tag:OAKYNPE+PzQhCP3wgnEeOw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
