namespace: pyroscope
resources:
  - namespace.yaml
  #
  # 2026-01-16
  #
  # Disabling pyroscope for now as its probably adding quite a bit of network latency.
  # to re-enable, simply uncomment these below.
  #
  # - service.yaml
  # - deployment.yaml
  # - servicemonitor.yaml
  # - httproute.yaml
  # - grafanadatasource.yaml
  # - probe.yaml

configMapGenerator:
- files:
  - files/pyroscope.yaml
  name: config
  options:
    immutable: true
