apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: mimir-ingester
    app.kubernetes.io/name: mimir-ingester
    app.kubernetes.io/part-of: mimir
  name: mimir-ingester
