apiVersion: v1
kind: Service
metadata:
  name: tempo-live-store-discovery
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: live-store
    prometheus.io/service-monitor: "false"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3200
      protocol: TCP
      targetPort: http-metrics
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: live-store
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-live-store
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: live-store
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3200
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: live-store
  ipFamilies: [IPv4]
  ipFamilyPolicy: SingleStack

