"modules":
  "http_2xx_60s":
    "timeout": "50s"
    "http":
      "preferred_ip_protocol": "ip4"
    "prober": "http"
  "http_2xx_30s":
    "timeout": "30s"
    "http":
      "preferred_ip_protocol": "ip4"
    "prober": "http"
  "https_skip_verify_30s":
    "prober": "http"
    "timeout": "30s"
    "http":
      "preferred_ip_protocol": "ip4"
      "tls_config":
        "insecure_skip_verify": true
  "ssh_banner":
    "prober": "tcp"
    "timeout": "10s"
    "tcp":
      "preferred_ip_protocol": "ip4"
      "query_response":
        - "expect": "^SSH-2.0-"
  "tcp_connect":
    "prober": "tcp"
    "tcp":
      "preferred_ip_protocol": "ip4"
  # Generic DNS probe for your cluster/internal services
  "dns_generic":
    "prober": "dns"
    "timeout": "5s"
    "dns":
      "preferred_ip_protocol": "ip4"
      "query_type": "A"
      "valid_rcodes": ["NOERROR"]
  # Crucial for Cloudflare Tunnels
  "http_cloudflare_tunnel_60s":
    "timeout": "50s"
    "http":
      "preferred_ip_protocol": "ip4"
      # Adding a specific header can sometimes bypass edge caching
      # that might be delaying the handshake/response
      "headers":
        "Cache-Control": "no-cache"
      # This allows the handshake to negotiate correctly without a hang
      "tls_config":
        "insecure_skip_verify": false
