apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: mimir-query-frontend
    app.kubernetes.io/name: mimir-query-frontend
    app.kubernetes.io/part-of: mimir
  name: mimir-query-frontend
