apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: mimir
  name: mimir-query-frontend
  namespace: mimir
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: 9095
      protocol: TCP
    - name: memberlist
      port: 7946
      targetPort: 7946
      protocol: TCP
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: mimir-query-frontend
    app.kubernetes.io/name: mimir-query-frontend
