apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mimir-query-frontend
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/version: "3.0.2"
spec:
  namespaceSelector:
    matchNames:
    - mimir
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: query-frontend
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http-metrics
      relabelings:
        - action: replace
          sourceLabels: [job]
          replacement: "mimir/query-frontend"
          targetLabel: job
        - action: replace
          replacement: "homelab-live"
          targetLabel: cluster
      scheme: http
