apiVersion: v1
kind: Secret
metadata:
    name: minio-backup-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mRJebXGiumMMwByM4912A2A5xSYu,iv:rAQtOGRxND4PDNsiE1uXckgxNgcCIt5TuS3t0mIQ7Ys=,tag:qSkS+eqTOigKi2aFehLFWQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qCDhMS/nSttNN7fGIe+4/XavpxNDgADklwHNkc1UVctflNxd1BLFxacL,iv:KMHUzSPM1InMRx7amIybefYl8O+aRiP72jKOabBl3o4=,tag:fvQhD8X9dqUYk/u447nc7Q==,type:str]
    #ENC[AES256_GCM,data:U2aQVvs6rINhIuMZFc19pp3en2WOBkcDadO4gzQSWY1j2f8gRG5yyLh0xGPWOxA=,iv:AjPhHnpw/KUWFVdXsi8MF9lMSZ/TAKwP0Zdm2dqsbvc=,tag:BPZ+4gX4El9Pi2zfsca79Q==,type:comment]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:x7uCuVa8Cw5sq6PCaq6JLuQFCgX+KmeXvGr9UNzwRdwNess4H+khQwsFiY7BNQ==,iv:1r/fZ2wZbGiumhV06fq7rKJLFkbc7/HglOfcwLwis1w=,tag:ho2OYVuhoARyYkQtBMbcfQ==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYytVYUFNR2d0VUVJY3Vm
            UWNMTGhwWGd6OGdzY0ZId2Z3bWNMRExvMjI0Ck9UamRBd0dnWS9qRk9lN0xURVln
            Y3ZFSk1ScWpDVVhkbGNJTFJDcWNYNDQKLS0tIEt3dHBXdjFjZzc5MzN2MTN5ZWtO
            aTJQSXU2Qnd6YWx4UENUNGxQTUhJak0KArvovicNiZuKyyWVk6iIk53Qh/ryAaTq
            eU7GPttz3yQhP/Tpz34w+dN1bnobv/O8lKcGE/65ICbMz3eb5VvEow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T01:02:35Z"
    mac: ENC[AES256_GCM,data:XVq3VNHAEUvkrLX8IdFwNQW3BYHQN1MytVDKb1U8sDkRe3bUUeASFcL6VV3HdQZfbtR3rTzyoLLjpviPPbrg/Xyh8+74J5P5vhDlAPsEmPKTqxsGYLXeY5nzS1aU8QeKUVTO8h6LO/8bDv1Y2Xirjeqvo+ETc/qNQpoLEWcFjEA=,iv:rVdQzsm2kw/Gl5oKex+G26ZDiSyNZvfzTPqv8k9n8iw=,tag:S+WHTaIfFJMjv4T95OMpyw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
