apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: querier
    app.kubernetes.io/instance: mimir-querier
    app.kubernetes.io/name: mimir-querier
    app.kubernetes.io/part-of: mimir
  name: mimir-querier
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: querier
      app.kubernetes.io/instance: mimir-querier
      app.kubernetes.io/name: mimir-querier
