apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: querier
    app.kubernetes.io/instance: mimir-querier
    app.kubernetes.io/name: mimir-querier
    app.kubernetes.io/part-of: mimir
  name: mimir-querier
