apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:9Vv5HdaaqBxnEWe/5oRkGg==,iv:fD/HK2Th+0yAmEcfDbEXh3hRSC/lNpJ7qJpnNkQ1Oak=,tag:atT+tXBX0ITzK0M0NPDmPg==,type:str]
    secret-key: ENC[AES256_GCM,data:wUuA5Qk+TIKfq3xFlF3YVhibAWoEl3c=,iv:R/XGdmPf9zoHoibFwLUB+GxHe0KJsp5OaFMJe6BCRLw=,tag:W0RBjHi4faoRYS/jtm4oDA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeWQ5b21OUUlJVHhFYzhw
            WHJaYjhIVGQrckVhd3V2WVV0eERkVEE3UkRVCnZWM3k3TEk3Qno2T1Z1WUlPQjNX
            SWJNMnY5SnVaUTY3QzNmUGgrK21rbU0KLS0tIG0rNzRBMmd3NTBFTnFybmlyM21M
            MUNwMlJnbzZ1Q3FleHZVVXgzNEZaUkUKUq2HOEtxFSBXFfSQf0YrZ8fbCY2bSbZI
            hbgryiXspr9SK2mnVBbq0Y50kWcBMH8ocdSmw7wVmDR5nq+doo8TSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T18:06:36Z"
    mac: ENC[AES256_GCM,data:1rH6fhtQnD7CMVUzD5EC03Te3DxLqOxl2q5rSmW71wZ1nMMzfk9J6A/GADYetq1cvCfqV1XVCsfADsUTovFi9q2LJWJWcZPyJUvPjBx1PzozDBZBbiUFc054A3lt1g00VdDZBeWhhAA+rhX7swCQJ5iU7sUDeZqgSDy74rfsy9Y=,iv:8r8e2TOggs1p4tI0pX3WcUafMNoJ2+jges43JNJ9xeo=,tag:j/ZVd4S/YrmeoxzKrKDdrw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
