apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: compactor
    app.kubernetes.io/instance: mimir-compactor
    app.kubernetes.io/name: mimir-compactor
    app.kubernetes.io/part-of: mimir
  name: mimir-compactor
