apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:b+lSo/GK9d1whxOoAnGN9w==,iv:OnnYnYHiclRbQOxbrTsQTSiNMHslfEoVWsmQ8M17AYo=,tag:3sTDATFlGVyiCBdBtsZjhA==,type:str]
    secret-key: ENC[AES256_GCM,data:h7g4M3K6WFjzlBdpV9tOmrc5yUNBqUmZFiScMjb4Gg==,iv:yCCwOM83eTR9GzUpSApe/rGSHYrkc+MAvwLkBI4fmhY=,tag:HR10ki9zqJUAoH8MAhmtfA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:01:16Z"
    mac: ENC[AES256_GCM,data:9s05Fm03rmGY8LqNY0VsEIFBVRQiwrGa0GXWqUBIwLLXS0zXdHmFkbI2t/9vYdW056L23ZH2M3oIPkBYXfJbZ5Ne5wEaxmecNBS+DJpH47l2nU7yiqgdQ7boZ5xHUmWNKQqoOwQBUvv1AAaYp8IFy7UXqJggUfGJjiMVSlwVghc=,iv:/CBnvXNOVQBd28pvVZbz+pZFfjIoSrqf3SY4Vgtp3UI=,tag:LZY1kx3ac8LgqkgzE+URhA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
