apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:eYp2F3GE6O+oT9jqXMJaKww=,iv:pCLk1Tp3JJRTQveQBwIdVIh3LoWsoyko8p3Talo1jLA=,tag:usRImvKeYr91zoDmoTv/3w==,type:str]
    secret-key: ENC[AES256_GCM,data:gW/6kaTQUk1lDQXiL1ypMTi7LqlrsIqY/pCXXZoOSWOTrm2P5ls=,iv:FYK4jRE7KKBszV1KdlHI3oFkrtFf0Cvd+ePJepH7zf8=,tag:VPVxHdJfG500JxpZj/Zvxw==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T22:55:46Z"
    mac: ENC[AES256_GCM,data:SVBEYkibsIbg5hWNDiTFnNI8awSmxBvMH9UnXkZG1kJ7vwWoSArEhieRt2KZTvNAIznVC0oKFfAnC+IkbLDER+Z3nCBDHJmot+WKELjyF5sJk4F9eKvTSTIXO/Ejg7RzvrPEGmElEwwXOrRy14pQEebY3utT2fYVNeytRtIiqpA=,iv:LKXPkxuMY1EH4AzVdhpQslBPXmiy4TSa0CsCLUJ6n9M=,tag:PmolG6UmNNwzzievrD6A6w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
