apiVersion: v1
kind: Secret
metadata:
    name: vikunja-env
type: Opaque
stringData:
    VIKUNJA_FILES_S3_ACCESSKEY: ENC[AES256_GCM,data:7NfNNw+7u6e6rEh+QKz4aw==,iv:Gpizzsf04cXkInPmyyMigbYB+a6KXB5/l+IGC4UP0iY=,tag:0UpA7BQzXVwbfHDFh/VOSg==,type:str]
    VIKUNJA_FILES_S3_SECRETKEY: ENC[AES256_GCM,data:bQAziiTRLL5YIzXwXb0YxwzpdX0UOLlVGz+K+uyP0AvKnp2yPPRAdpY=,iv:9HRHMFs5h0Wc0YOHw8V08cJzUP2NiCPOFUhe7VoZL0g=,tag:7anhw7SyUrfIY7qH9yosMQ==,type:str]
    VIKUNJA_FILES_S3_BUCKET: ENC[AES256_GCM,data:O68xdQHVWA==,iv:a4dwULPamDPaGfez68yuMmooq6PI0K2IiDpQlx6H8YQ=,tag:IFy5YuN8mFD5qC1Nf6Hqcg==,type:str]
    VIKUNJA_FILES_S3_REGION: ENC[AES256_GCM,data:De2w9BafALjz,iv:QO2vBx0U1ZGqZ5aIpe8e9Hu5lMGfLXXjNUn4Atrdodg=,tag:gQ748EDy+lHOhGZYLBAaag==,type:str]
    VIKUNJA_FILES_S3_USEPATHSTYLE: ENC[AES256_GCM,data:RdNEUw==,iv:jt209HF1cbiKPAlKutuMpkOXcBdUvm0WY1fh9MOl8Ow=,tag:3O6M9jnASv7iIl3bfD+lHg==,type:str]
    VIKUNJA_FILES_S3_ENDPOINT: ENC[AES256_GCM,data:P6Aqhk/mduI6cKm6xRvGqyXeHtpL2v5NtkIL/IGomSFbVllyrTQhiTkglbUi,iv:wM8USjZ0qL+Y3HnnObNGTSMA9a3KKxi/U3rrMHZm6yA=,tag:07cKp4EN/LqNEXqOWVbV1Q==,type:str]
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:tPRD/iLxfdSnlA6tCWcVHgl1qx6F4RytG5ytSQuZzDpxvfENJNpIYpSvrQzJuP//INhQeUUv6OEkNouuPmeQQQ==,iv:zVVulmFKTEEEOfWhkKh4ZmhYjYP8K4MM46oNCzJsC2g=,tag:J1ET+XRLFEIg29/Lrldl6w==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTID: ENC[AES256_GCM,data:tbvaaCvRxQ==,iv:9RvTnWjtHweLL+iTAZ75B1BYXS2DSBYsj92FAbH4V0k=,tag:vum4VHngNlrb1FsWLagN8g==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTSECRET: ENC[AES256_GCM,data:FhRMxBcIJkhsFf+xL2suBN5shQLiUoGLDvyj50IIobEW4zCElDU0X0zwy9eL9FnUJrBsw4t0mvw9OclJ/KM9he/Wajaujo8x,iv:R5kGboRra7hDDMpXOOKfsfQbk5Rj/1pCDxnopj1JpLY=,tag:B5gIAKWSymWgq5LbnJxAXw==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza2RwSkt5SVEvS0pQVTVn
            K3dNdHgxcDkyT0pSanpFbDFMMEhWU1FZcUZvClFlZGlYbG1HZytSM0lIZlhKckRZ
            ZXh0bmNCd0JPWVduVVBYMHJBWXlNZ28KLS0tIHJ6U2thME5aK2VaZFhxNUt2VGZ1
            bVV3YzE2UUxQRGw4UDBJQVlpRnExcFkKZxPkjMfqh4RA6tPt2xfUd/G165Z3lNXj
            FLMi+m2fcQg4SE7JvAcZtEsGajkPDlW2Edmbczq6Ik6iWRvjNkIVoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T23:57:55Z"
    mac: ENC[AES256_GCM,data:EaAbOFusssoPwpIHLRFsJ+dnf8qPQcUZj2lWug7PEiJPpNHIHhhB07z7mbTx2VyIP6Qr5NjW3wDv5Bt+gjeNX6LPWeq37pX6uKpAj5RkZ/jkkC5Io1RjEPBKJBpc8rdE0OBMMk/Oi08wHExuxQ2h8gb4oMrP/w1ynKnf8Sr9ixk=,iv:ikBYRKyDQBOLfXhYi2dn+C2rFmn1vjRoVls1J1ANGkM=,tag:C9yD++d8b2cP7LdlhwxeIA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
