namespace: prometheus-operator-system
resources:
  - namespace.yaml
  # - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.89.0/bundle.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.90.1/bundle.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
patches:
  - path: patches/controller-delete-deploy.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: kube-prometheus
