apiVersion: v1
kind: Secret
metadata:
    name: immich-env
type: Opaque
stringData:
    IMMICH_LOG_FORMAT: ENC[AES256_GCM,data:RKaeUw==,iv:49RmUgjay2Ul7Stbqf7URQeiXKKuhi5eHNL0+urgB7s=,tag:JiYwBbbMqvJ7OS42jOL3vA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVWNldkxiNVF2dk5JVWhF
            RnlJYkhXVFFmYTc3NktBRWt2cC9mYUpqNFhjCnJjM215WEIwNXZOUmYxekI3ODRn
            bi9XZGNPZ2Z4aEVZOTY3ZTcxUjloRWcKLS0tIDlRK0lFRm1HNkx4RnBndUdQQlg5
            UGhrOG1OQ1VQTjRFclFSQUpsVjhoWkkKM0P58V6OQuXRuNzkBi5Bzx1Bjlkdgxvs
            /LBG2MxGYjOiPxtdp/mK+0pvPEljPDna3gmvyaET6/QAi+iqFxq0nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:10:53Z"
    mac: ENC[AES256_GCM,data:Vk218miUwCRvpEcFPFfE/ecCIkNQOk9JT8lXh9iGsyGHiLKdk5gLdkFD2aX5vlk8997HZp1vWAv8ro/bZlZcyAi6yDK528ixfkvnh82PP8V/bi7P+lSFuVFqhsWRXp5ITee+zy4WKc6EPrP8n7zyzRuybEkqvkwChKAveu7UHnU=,iv:t+eerBp7A/ZzkBYNmjwcQb1lVcUC0zFHevQQ8ZtDU/Q=,tag:ugMnltZflnLB71Zh7/3rSQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
