apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailpit-data
  labels:
    app: mailpit-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
