apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:3DH46dKzNuM6WHxwabuu,iv:/4pkG48e7zVAu8z+3mAVtYoKzUeFCney6nTuYW2Et2U=,tag:fo3XW6zLLisB13OrN6ylxQ==,type:str]
    secret-key: ENC[AES256_GCM,data:QhSOX3I0hTSEL8qk70c2i+Ax1oVpYuKWAoBvrzvgb2p3qA==,iv:QB0nc78Xcohl2N2JS7tRYZ3iEyc1JSEr3BM/jDW1XKg=,tag:lAuUwUBtpG59ut4gEUSziQ==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T23:27:19Z"
    mac: ENC[AES256_GCM,data:AntuRqR6c4HxUmgaibhZiruPgvXKc03g7ikEQObff5APKVbFK4eyw0SloJ4b3NdRe4EwEK/3wRN/i4gOpNaAGizxd6tM3h7++V3zTYpLy7Q9bTYLGMg2HbLHYMFbo9DpzJhhfmBdpaxjyxO6Z0MtmSiWkn4tO6no/W5WWRVGc/Y=,iv:NmoRkuiSMvIVthSKsxE77Oh043eWpfli1sAqcyLvS9M=,tag:vtI+5nFPJqAi1nEw9R/ldA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
