apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:tWwHja+/66L74ZX8J2kcBA==,iv:vcwDie+MeoTpCVYjwscmfvj3G47QmmGwcxlihRrijTI=,tag:ApJkDpQ0LNZfWKV8faksMw==,type:str]
    secret-key: ENC[AES256_GCM,data:nId5Z9ucd13Xd+bFbHojT2O8qC2RmHKPo2kxQg==,iv:aZ9gH4qWGjv+4W/bAi4L7FJ949/EiOPi0OZwVPwxgj0=,tag:bhMMgZG2f7BvnsZ5hCu3KA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:15:46Z"
    mac: ENC[AES256_GCM,data:ifKPsS27SOjyd2ddwvs66xTwSUGkT16K/d14t2uB3dSoMXFz4zDEUTltLyCdMqkxpJq5CAKQ5VPje6IE096lwpifd/Njv5d1udyO/OgyvLCadMy20YmPXBSVmGEXdUEc9SfcA5JWyDf+H3i9ASn7fkjrKSg2LQaqBJGZZukzpvU=,iv:8P+ozwIhg83/HTeTlX10+8ulnHhzqyDdFcgledy9t/Y=,tag:MjAfRQILL1oanldSd87e9A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
