apiVersion: v1
kind: Secret
metadata:
    name: searxng-env
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:zhnmXME6NcYWN5VBbv5oR9t4vF0bT1cCZlDB2TEtfwgBSLpiWtMIQBXHIkxR0VgagfBE53Zqt5QG0Y6tCysavw==,iv:+KgzcPlNWOL1l8ZVIfVDGSp9bqUHwPEKmHFJZzq5bSA=,tag:icI1CB1yAfGHN6MfePk3vg==,type:str]
    SEARXNG_BASE_URL: ENC[AES256_GCM,data:bvuLDQiZuuwFV3sRNQfnrRPxY3XZnNOIiq3x1Jc=,iv:ikMOHQkWkv7vscZ1+FazdwYdNLA7LvxNnbywMXgl6Y8=,tag:502ydmMJvY452rPvLVEgDQ==,type:str]
    SEARXNG_URL: ENC[AES256_GCM,data:UXMR2J718J96zDwKyBQ6oos6I7jfAFHM474KlX8=,iv:mpfFwg34JtGafcsYCLTykPPKM/pBfDKQjTiYSL000G8=,tag:VbR9OID4nZtFeO5ixEr+ug==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTG1VWDRUSWRTZitHVGI2
            RFJWbjFuc1RyRENuTDNPZWU0MG5TdTZpL3lRCnZ6QVdRcS9zeVNWbDNOaWtKTlAw
            SnltRHlhZm8wQlJpMVhBZmdGa0Z4ZWMKLS0tIC8yeUxHOUVuaUhZWlZkTjcwdzBV
            NzJoMjE2aUVTTjV4NjY1UnNGT0VFaEEKh7IHrn26rezjIW+ON2AvxYgb9FHFn7Z1
            xR+mQuf+B6q+L99Sa+UQN2H/5xpGQdo9ym9uLIh1o4Tebd6QiiMtAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T18:03:14Z"
    mac: ENC[AES256_GCM,data:Qp33AUH5vMsuA5b+sgJzSFv1GDj1mVV/vkaoTmDVUER0IAVpDo5sp2ZnpgJZDEt+JndXnxeuaivpDY3gOb0MuDsXJlB4vei4+t5wsorhHh/hINBf8jOxA68R0qEOb2RqHN9g7A6/TDWlhZy251hSKh7KxnOvXxuKxTpjNZnaf+w=,iv:6vRVi5N7CKZSI/1T8VlnnZNA2bTehNfq9Ym2lFVAt9E=,tag:1D7vkHF7C3FgRXxLGZpdOA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
