apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-ruler
  labels:
    app.kubernetes.io/component: ruler
    app.kubernetes.io/instance: mimir-ruler
    app.kubernetes.io/name: mimir-ruler
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/version: "3.0.2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: ruler
      app.kubernetes.io/instance: mimir-ruler
      app.kubernetes.io/name: mimir-ruler
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ruler
        app.kubernetes.io/instance: mimir-ruler
        app.kubernetes.io/name: mimir-ruler
        app.kubernetes.io/part-of: mimir
        app.kubernetes.io/version: "3.0.2"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mimir-ruler
                namespaces:
                  - mimir
                topologyKey: kubernetes.io/hostname
              weight: 100
      serviceAccountName: mimir-ruler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ruler
          image: grafana/mimir:3.2.1
          imagePullPolicy: IfNotPresent
          args:
            - "-target=ruler"
            - "-config.expand-env=true"
            - "-config.file=/etc/mimir/mimir.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: storage
              mountPath: "/data"
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mimir-objectstorage
                  key: s3-access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mimir-objectstorage
                  key: s3-secret-key
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://trace-collector.observability.svc.cluster.local:4318
            - name: OTEL_TRACES_SAMPLER
              value: always_on
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir-ruler
              app.kubernetes.io/instance: mimir-ruler
              app.kubernetes.io/component: ruler
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: mimir-config
        - name: storage
          emptyDir: {}
