apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ruler
    app.kubernetes.io/instance: mimir-ruler
    app.kubernetes.io/name: mimir-ruler
    app.kubernetes.io/part-of: mimir
  name: mimir-ruler
