apiVersion: v1
kind: Secret
metadata:
    name: lldap-env
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:DKbGhjA3E+HjCpVb945MHy7IDSGDI+rvgceaVCWjqUXoq/Ho0pMAvgwx5aBHaiHFxUyE7GZE8NKofbQTqc9psA==,iv:WhCUmu3yfU6H7ivAPTOHahkiSLxuvVqXwSuKU4RNhIY=,tag:fc/nY9TmRDt4Oy4pbXOY/g==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:2RhbP5PNUcHyhYp9xeeL54asviBhsSZfGZVPm880t2wVhhw621bsTw0k2eyoY3bOaxWCuiUQQp5V6cJKTrD8NA==,iv:SPAJXZbo4XduOz06HYMiJyC6V3qY6GStRHQ9i532syE=,tag:2+PxDnHdUtymwCl+dvDj7w==,type:str]
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:2LOTC0q7SzvBs8mQen+mQPSM3BqcoA==,iv:0sbA7EZsxQih9RyUITrSCNVHpqoXFQYQMxxMNKJS9RM=,tag:39YsHd4NE4lGo0u8A33Cyw==,type:str]
    LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:Y3WxGfWBoOOyBg==,iv:YjHeLxGM4VqitPbsQbtA6HGhW28OH7Heen7LlOjM8hA=,tag:cDW10jMXap/c3AQSNkLcVw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Qbjg8CYDAdc/NATeuYfozH7sfg==,iv:NBuZhA5HIaHGznKSVONXCLmjbCTKc9/r3EOXNSFKuvE=,tag:56TEL3BkvoBzG6i0mNz7tw==,type:str]
    LLDAP_HTTP_URL: ENC[AES256_GCM,data:6baUUYXYB+kaHfNUnAK6sci+SDNHDWYaOL5e,iv:/4BvFbTwbWIDvOmKXXb4qkfwDKHpy3HUV06W5/3w/AA=,tag:3SOGeABhZ+KgzHewtIRBDA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aEVKQ1IwMXlmNjd6cVdU
            RWY1TnhENnZaWkdRMmt3cDRSbkIxNVlvWmtZCnZzQXVZR0gxMDFQaXNBaHZheVhF
            WEZFR1Y4eUMyMi85SDhkckVTN0Y5bmsKLS0tIFFJeGFBZHVhY2h3YVlOWjN4b29F
            WHlIVGtKV0dWSXE0SEd1Q3paZnY0amsK1C+ARiRC0yWOscbBEZufefllsdK09fqn
            OXiOGdjSMqgVmlO/162QbRkXj1p3NFUJjIZxd2pnJimcU3s8vo0uPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T18:04:57Z"
    mac: ENC[AES256_GCM,data:4KlDWi3Np7AHyfJ4nOJrpwFS3GmgXSGlaKt9ffm1J+rtmshZlRLukcPw6XZpL85PkFQoD1Mt58Vp/eJ136Wog8IQXxptPUT9MWYtwrdazSttOqvYj7nMn5oS8xf0bRsIUMmYYq7H8NsjyH7kMO0jqweAVHvHADrEIkjAltz9kRY=,iv:smB3FvNBXJxOiuzdxzwzqBZYSURqNX2KxJBrzrVkmYI=,tag:t2k8NTMY2rsf5XY/cyGyuw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
