apiVersion: v1
kind: Secret
metadata:
    name: registry-env-secret
type: Opaque
stringData:
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:pz4Y/JR2ORAy483iFHwi/9d3yqY=,iv:IF8j5Q+NdOT8/4DdyjjVuDpT62P1oLmRqUagUedwBdI=,tag:b+8DgWWahqof4B2iakGSlQ==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:GzHLrFm089n2GYiS9C0MGxXNqapBGyQkf4YS7w==,iv:u0CrbiuPvvV2XEvXZuI8BPaXgMdliYGYSRm7H2GfQ0E=,tag:gUlNL6av6Lv5ZmMKC34nVQ==,type:str]
    REGISTRY_STORAGE_S3_REGION: ENC[AES256_GCM,data:nwUMfBMc2zP5,iv:/8W9LcxZppnS6pfzVyw5UI2XgYrAX7TlJURZv8BdX5k=,tag:pE7U3WwqwsWlKdDtsndwTw==,type:str]
    REGISTRY_STORAGE_S3_REGIONENDPOINT: ENC[AES256_GCM,data:qvJkJCM/qSwzdXFreqEAMewfkZj9V0BUAeRExR00p7oQqrpFFZMXUAE07bKH,iv:uhtJnzXBYPqHoqurH8an0wmA9dkqNKRQRsbnDMq+5/Q=,tag:Mgbl3/upGtcJAC6KNCf3/A==,type:str]
    REGISTRY_STORAGE_S3_BUCKET: ENC[AES256_GCM,data:wTyd5Auynmfc0cYGKAHE,iv:NGEINXznIfTHSDv3naGn7XCQJotBHA5rv1GlaXCnlUI=,tag:8VZfUFlg0lE4doowJ5wlpQ==,type:str]
    REGISTRY_STORAGE_S3_SECURE: ENC[AES256_GCM,data:fAp7E2Q=,iv:h3NjrpIw2ELpESlCruRp45aeh6qmlhihtR0Miu32PHk=,tag:5VFvPGPJwt4shmRY5kGrzw==,type:str]
    REGISTRY_STORAGE_S3_V4AUTH: ENC[AES256_GCM,data:F51FFEI=,iv:Il6jEzo/tzGy7Y7YWYmY95NiqK2f+XXXeBFT9og8Kc8=,tag:VmLkk1bMMWKa2GMUJXt1ug==,type:str]
    REGISTRY_STORAGE_S3_FORCEPATHSTYLE: ENC[AES256_GCM,data:O1okRA==,iv:DUSrpWKaxUizP9RJwOezeMe5yvpoA/+4bNRMWfA8S1E=,tag:oAAqf+PWJT5MRFlEsADHYw==,type:str]
    REGISTRY_STORAGE_REDIRECT_DISABLE: ENC[AES256_GCM,data:SvIB8A==,iv:xqIEf3PEiMrmDO7sapXn+LuvjCxTpGXRhMMvbriqRnw=,tag:CKf4McgAZqQxlt3mp/3Q7w==,type:str]
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:zdhGeOhWhpFgo6pC/vmLeDC8P5s+Ww==,iv:cwC9yUEY90eOn37RPN1DuCzehtg9ZBRCWAEJktFVJ3A=,tag:U6bpyIKkD+cV1IImaGQuQA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ2ZWMHpVMzc4dGxYbUdY
            S0xCT3VoYTlZVWZXSC9jZW5lZmdqbUhmSnp3Ckl0TWdUelYzeWhlcXFmaDFhOUpm
            cFRNNmZzNS9obHlpajU3NkNCOENFWHMKLS0tIFZwcGlpV3J5RWt3R3owbENzc2F6
            ZEc2Q0pqWHpsNmRjcE5zK2N2K1NTWEUK79m5FRgNf0K/fAqdH3PJa88OlAWgK4F0
            NpEQKpM3O+slmbipw1jqx+mTaKmqAWMul2kSgltQGKJ2WCCGcGAJpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T05:34:20Z"
    mac: ENC[AES256_GCM,data:V10Ky5E804yYuUJzUVaAf8nG9AZ7MYq9THQIboIAF9bYRoFQIbHlZPP8MIQzMWgMyetzHjDzTpHUE9Sl8nruNB/C9kx1AZs7vOoPTEiQVVsskEp6lVTOh7VQ8B38KCjGgDWYZYT17burmBYxZuzI9Hgt/yttQ2QUMHn+DjStKgM=,iv:0lY3xiGdqijVkCPEsIaJf4KJ1SScWFoWJyW/73MFPY0=,tag:DZoYa+a/3+uxNYGKlq8UtQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
