# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: docker-registry
#   labels:
#     app: registry
# spec:
#   selector:
#     matchLabels:
#       app: registry
#   endpoints:
#     - port: metrics
#       interval: 30s
# ---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: docker-registry-s3
  labels:
    app: registry-s3
spec:
  selector:
    matchLabels:
      app: registry-s3
  endpoints:
    - port: metrics
      interval: 30s
