apiVersion: v1
kind: Secret
metadata:
    name: kanboard
stringData:
    db-connection-str: ENC[AES256_GCM,data:dW29KnAmJrCmb28WzryknQAPIQtUzGzSZcfTedhSdjN+nVabFkd6579yYypr/KpMTTzGymxy37Vl9lBxZ/Wiv8sFxjHGidn8xB2bkIY=,iv:RMzZil73/WVhgO3tNAK9LPIXFEWheBqkFf99oEfzHRM=,tag:dRRce+EscEK7hL7xn3YCRQ==,type:str]
    #ENC[AES256_GCM,data:0ehEfDgGYZQRI/XDG4h91UuHWL7nIr6vjVzvIkXbd5RbrpYsaj9Fj1SOIvOFOq40kDofGOXWXJ76IAQVT1rDKEqbdQ0KuVtX7VxnppLxoWGSAfC1EwQavWvR5w==,iv:8+/UdC2i8Ex00RJU8y7WQu4wvq0b3BsJmulbymYlpk0=,tag:K4nIXzGbk++SSc1lyt9czw==,type:comment]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYWxkUnUrWThTb3VjRWN2
            eGZMaEtYcDQzZll6ZEg0VlFnTXJCNWREYzJvCmZHRjZwNnVzc1dVKzFIRi85bFoy
            YkFGT1psYnhHMExQT1l0dGZBWFNBWncKLS0tIEFqWHJPY3RaSzA5ZEFwRmNQUGxC
            WkJWWDE0aEFMSHRkemRaNmNYRWpzNkEKz8FC0HWEZyfSzUcrmsdiyoqOOlD1EMJS
            HqdzmcePgEXgX7pg0W2ttMjV0m9reF85zfNs+hmcddoMtpM9+cTxfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T01:44:54Z"
    mac: ENC[AES256_GCM,data:xoFDJEuf4iZsK45nqb0diUDicztIfyH1MTJe06y3O63qamb11496G199yxzw/hlRn4pFds9FcXM7WEXNgE8UAMMa0CStaIf+q3b1U62VI9xXyFXdL/rIhKrqMbxjP5d36ElRWo3mae2hKn62iasvPf0Z9cdYTlzTTmK0djb3XSU=,iv:cDNIz/jBHuDJoZGInW4AXFbeEhsln8h+hsXTZldrdVs=,tag:rmnWJl1a9g13kqyG+qOfyQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
