apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-server-httproute
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/name: Immich
    gethomepage.dev/href: "https://immich.home.alden.ai"
    gethomepage.dev/description: Photo & Video Management
    gethomepage.dev/icon: immich.svg
    gethomepage.dev/app: immich # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/pod-selector: >-
      app.kubernetes.io/controller=main,
      app.kubernetes.io/name=server,
      app.kubernetes.io/instance=immich
spec:
  parentRefs:
  - name: default-https-gateway
    namespace: istio-system
    group: gateway.networking.k8s.io
    kind: Gateway
  hostnames:
  - immich.home.alden.ai
  rules:
  - backendRefs:
    - name: immich-server
      port: 2283
      group: ''
      kind: Service
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
