namespace: kube-system
resources:
  - scheduler
  - apiserver
  - coredns
  - controllermanager
  # Disabling this service monitor since this *should?* be working via in in-spec kubeletstats otel collector daemonset. 
  # - kubelet
  - kube-proxy
  - rolebinding.yaml
  - role.yaml
