namespace: authelia
resources:
  - redisreplication.yaml
  - ciliumnetworkpolicy.yaml
  # - redissentinel.yaml
  # - grafanadatasource.yaml
  # - servicemonitor.yaml
generators:
  - sopsgenerator.yaml
