apiVersion: v1
kind: Secret
metadata:
    name: authelia-redis-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:VkkLUH7YtBtVT0sUoEdkP876OpxLKXO+2R0xhT6UArpoKwsVkNQFF1H/g8/RRdLx9+0T2MEj5iNRE51gey/5iw==,iv:pq+Dy/LvWH7LfExYXZwYiT/BHxWAwQ5887Fp/fDtSC0=,tag:I+cUHmnk7WiNak/nAJAKdA==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTDJ6UE5nYzNPcnNtQlNx
            Q3pnMkNROHJJaVRjS2lhK2thSzZsc0ZwcUNZClU3ekpYMEtvbDhnblNNdFY2a3ZO
            cEJETWNiQlVibW5EUWkvSldYVWtYUmcKLS0tIGdUY0plY3hraVQ0V2szQlhjWDJ6
            UDZjR0RhLzVGSStheE55c3hsMmhJZ1kKREpK7OHzMaVRXG6d5qS40qqOzcNJu4wn
            2u8wZEZyCoWnQIf9GO3Yi4v6Vz413hnw9wBY9OfYSYnowpCFajHguA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T19:53:49Z"
    mac: ENC[AES256_GCM,data:xc7QN27VZ8LQpFiqsEro7oaVurtslc1od5SJhkN1cJge4wpckoK1L0V2sm7xWN6UhTinJlB8ecRYElXQXgUux4hs5PuhdUo/cFXIiUSgxBYXxxBebRaozzuytWZ4HsVAk4QPe5tv8KyH8G9l3n2paHK+asVLQJtAVV1r96HWPWs=,iv:vNtA5OA9S19VxtS2kfS+bncha8ayhZWrbAs20TuoXYE=,tag:nbxRNrWFqKS6rniKeHhaew==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-redis-sentinel-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wmQ8tDxGh1Gvam4uBzoq9QtsTuIv4JYbEbPSrq9sScsyP0/J04XUB13sqgz/Loi94Z0sFM/+M94QvSLxUIlO6A==,iv:mYOpJLLjfil1QSna+miOmq+Xi5AywnBOg/1EsCKrAZI=,tag:E4avJTKXF6qja27zDdzqYQ==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTDJ6UE5nYzNPcnNtQlNx
            Q3pnMkNROHJJaVRjS2lhK2thSzZsc0ZwcUNZClU3ekpYMEtvbDhnblNNdFY2a3ZO
            cEJETWNiQlVibW5EUWkvSldYVWtYUmcKLS0tIGdUY0plY3hraVQ0V2szQlhjWDJ6
            UDZjR0RhLzVGSStheE55c3hsMmhJZ1kKREpK7OHzMaVRXG6d5qS40qqOzcNJu4wn
            2u8wZEZyCoWnQIf9GO3Yi4v6Vz413hnw9wBY9OfYSYnowpCFajHguA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T19:53:49Z"
    mac: ENC[AES256_GCM,data:xc7QN27VZ8LQpFiqsEro7oaVurtslc1od5SJhkN1cJge4wpckoK1L0V2sm7xWN6UhTinJlB8ecRYElXQXgUux4hs5PuhdUo/cFXIiUSgxBYXxxBebRaozzuytWZ4HsVAk4QPe5tv8KyH8G9l3n2paHK+asVLQJtAVV1r96HWPWs=,iv:vNtA5OA9S19VxtS2kfS+bncha8ayhZWrbAs20TuoXYE=,tag:nbxRNrWFqKS6rniKeHhaew==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
