apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres-18
  namespace: grafana
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3

  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  storage:
    size: 10Gi
    storageClass: local-path

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      enabled: true
      parameters:
        barmanObjectName: minio-store
        serverName: grafana-postgres-18-3


