apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: openbao
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bao-ca
  namespace: openbao
spec:
  ca:
    secretName: bao-tls-ca
