namespace: openbao
resources:
  - namespace.yaml
  - openbaocluster.yaml
  - ciliumnetworkpolicy.yaml
  - issuer.yaml
  - certificate.yaml
  - clusterrolebinding.yaml
generators:
  - sopsgenerator.yaml
