apiVersion: v1
kind: Secret
metadata:
    name: aws-kms-credentials
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nrMPLnzPQXxRrfWFldrzAkIxBzU=,iv:FnJdA6g58X7g6vvzdjIF5xW87mXupNS2ErrDN27IIyE=,tag:0c9DCYXwqNegmw6THRXBwA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BCtvZJGfdrH0oeWq2qdjBsA3x3m7Ix8e6YoodnHGkjQK+Xn3Z0bIeg==,iv:FCoDQfevVS+SY1jzMHoaBDHxcZycOmieudZNtRXxLLQ=,tag:i+uO77+t0nhAK/7ALMJ1ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVWZSblhvRHNaNmc0SFVU
            cUgvRVpOamhpcVNqNUlWNFp1RndKTHZhZUJZCjFQYUJHRlVmSE1wSW5jMk5kaVdT
            eFBRQ044b1pXR2w3bEp0Wk8wZzJKaUkKLS0tIEtxYnc4Q3NBNmFyVDUvQlhFV3pt
            SGQ5KzNKVzJsM283R3U0N3I1bE13b0kK7+d82uBx0C7QBJNQK9LVgp1qo6mdulTt
            saLiW3j+NBS8NB2ECK29Cjwb+XG04wInHUlop0GDn/Kz62t3Yg8L3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-10-06T18:36:10Z"
    mac: ENC[AES256_GCM,data:YjbxKTJW7b4jx63osem2bs5DB7zZ9xg41NM8XiGksalOrV1scLVMUmMfRu9Z2SKeXD6bR0r4Y9DJwOZQG08UAhG7U/ZxKhFjNXvJj916sJt0+CFLvrgXmnZH4ZLdamx9n63BfkAhBuFhoArgBAmiJy2Qrm5yNRjfZvTu55w7XYc=,iv:qLnAEtvxbs1MjHiTs6SvMjWV+2JpmIHauG7tAzXQDbI=,tag:cZ6KT3MmwBo3zbqGZzARnA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
