namespace: mimir
resources:
  - servicemonitor.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - statefulset.yaml
  - serviceaccount.yaml
  - grafanadatasource.yaml

generators:
  - sopsgenerator.yaml

configMapGenerator:
  - name: mimir-alertmanager-fallback-config
    files:
      - files/alertmanager_fallback_config.yaml
    options:
      immutable: true
