apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir-alertmanager
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/version: "3.0.2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: alertmanager
  updateStrategy:
    type: RollingUpdate
  serviceName: mimir-alertmanager
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: storage
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/version: "3.0.2"
        app.kubernetes.io/component: alertmanager
        app.kubernetes.io/part-of: mimir
    spec:
      serviceAccountName: mimir-alertmanager
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: mimir
            app.kubernetes.io/instance: mimir
            app.kubernetes.io/component: alertmanager
      terminationGracePeriodSeconds: 900
      containers:
        - name: alertmanager
          image: grafana/mimir:3.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mimir-objectstorage
                  key: s3-access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mimir-objectstorage
                  key: s3-secret-key
          args:
            - "-target=alertmanager"
            - "-config.expand-env=true"
            - "-config.file=/etc/mimir/mimir.yaml"
            - "-alertmanager.configs.fallback=/configs/alertmanager_fallback_config.yaml"
            # Prometheus HTTP client used to send alerts has a hard-coded idle
            # timeout of 5 minutes, therefore the server timeout for Alertmanager
            # needs to be higher to avoid connections being closed abruptly.
            - "-server.http-idle-timeout=6m"
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: storage
              mountPath: "/data"
            - name: alertmanager-fallback-config
              mountPath: /configs
            - name: tmp
              mountPath: /tmp
            - name: active-queries
              mountPath: /active-query-tracker
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 20
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: mimir-config
        - name: tmp
          emptyDir: {}
        - name: active-queries
          emptyDir: {}
        - name: alertmanager-fallback-config
          secret:
            secretName: mimir-alertmanager-fallback-config
