# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---

clusterName: homelab-live

talosVersion: '${talosVersion}'

kubernetesVersion: '${kubernetesVersion}'

endpoint: https://192.168.123.50:6443

clusterPodNets:
  - '10.244.0.0/16'
clusterSvcNets:
  - '10.96.0.0/12'

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

domain: cluster.local

allowSchedulingOnControlPlanes: true

patches:
  - "@./patches/global/machine/longhorn.yaml"
  - "@./patches/global/machine/kubelet.yaml"
  - "@./patches/global/machine/features.yaml"
  - "@./patches/global/cluster/kube-proxy.yaml"

# Controller patches
controlPlane:
  patches:
    - '@./patches/controlplane/cluster/metrics.yaml'
    - "@./patches/controlplane/cluster/admission-control.yaml"
    - "@./patches/controlplane/cluster/apiserver.yaml"
  schematic:
    customization:
      extraKernelArgs:
        - talos.platform=metal
        - cpufreq.default_governor=performance
        - intel_idle.max_cstate=0
        - pcie_aspm=off
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

worker:
  schematic:
    customization:
      extraKernelArgs:
        - talos.platform=metal
        # The newer nucs don't work with this one so this is added just for workers (older nucs).
        # BUT remember that newer nucs added as workers must have this removed.
        # - i915.enable_guc=2
        - cpufreq.default_governor=performance
        - intel_idle.max_cstate=0
      systemExtensions:
        officialExtensions:
          # - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

nodes:
  - hostname: worker-01
    ipAddress: 192.168.123.101
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:8c:9f"
        addresses:
          - 192.168.123.101/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-02
    ipAddress: '192.168.123.102'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:8d:f9"
        addresses:
          - 192.168.123.102/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-03
    ipAddress: '192.168.123.103'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:7b:b6"
        addresses:
          - 192.168.123.103/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-04
    ipAddress: '192.168.123.104'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:7c:60"
        addresses:
          - 192.168.123.104/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-05
    ipAddress: '192.168.123.105'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:8e:5d"
        addresses:
          - 192.168.123.105/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-08
    ipAddress: '192.168.123.108'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:63:a3:23"
        addresses:
          - 192.168.123.108/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-09
    ipAddress: '192.168.123.109'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:b6:6a"
        addresses:
          - 192.168.123.109/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: worker-10
    ipAddress: '192.168.123.110'
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:4d:30:64:80:55"
        addresses:
          - 192.168.123.110/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 250GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          maxSize: 250GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          grow: true
          minSize: 150GiB
  - hostname: control-plane-01
    ipAddress: 192.168.123.141
    installDisk: /dev/nvme1n1
    controlPlane: true
    # This is the node which runs jellyfin, so it needs to have i915 extension while other control planes don't.
    schematic:
      customization:
        extraKernelArgs:
          - talos.platform=metal
          - cpufreq.default_governor=performance
          - intel_idle.max_cstate=0
          - pcie_aspm=off
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:74:ad:d1"
        addresses:
          - 192.168.123.141/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
        vip:
          ip: 192.168.123.50
    nameservers:
      - 192.168.123.171
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: '!system_disk'
          minSize: 1000GiB
          maxSize: 1000GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: '!system_disk'
          minSize: 2500GiB
          maxSize: 2500GiB
    patches:
      - "@./patches/nodes/control-plane-01/ethernetconfig.yaml"
      - "@./patches/nodes/control-plane-01/sysctls.yaml"
  - hostname: control-plane-02
    ipAddress: 192.168.123.142
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:60:7c:ac"
        addresses:
          - 192.168.123.142/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
        vip:
          ip: 192.168.123.50
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 500GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 1000GiB
          maxSize: 1000GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 2000GiB
          maxSize: 2000GiB
  - hostname: control-plane-03
    ipAddress: 192.168.123.143
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:61:0f:20"
        addresses:
          - 192.168.123.143/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.123.1
        dhcp: false
        vip:
          ip: 192.168.123.50
    nameservers:
      - 192.168.123.171
    volumes:
      - name: EPHEMERAL
        provisioning:
          maxSize: 500GiB
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 1000GiB
          maxSize: 1000GiB
      - name: local-path-provisioner
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 2000GiB
          maxSize: 2000GiB

