namespace: node-exporter
resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  # Removing this because cilium actually uses it and we want network from otel and thanos and elsewhere. Probably delete to be concise in the future.
  # - networkpolicy.yaml
  - prometheusrule.yaml
  - service.yaml
  - serviceaccount.yaml
  # Removing this because the kubeletstats collector daemonset is setup to scrape it, otherwise both that and the core-prometheus-collector deployment will scrape it.
  # - servicemonitor.yaml
  - grafanadashboard.yaml
