apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: mimir-gateway
    app.kubernetes.io/name: mimir-gateway
    app.kubernetes.io/part-of: mimir
  name: mimir-gateway
