apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: mimir
  name: mimir-kafka
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
