apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: mimir
  name: mimir-kafka
