namespace: forgejo
resources:
  - namespace.yaml
  - postgres
  - redis
  # - runner
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - tcproute.yaml
  - persistentvolumeclaim.yaml
  - servicemonitor.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - probe.yaml
generators:
  - sopsgenerator.yaml
