apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-querier
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: querier
    app.kubernetes.io/part-of: memberlist
spec:
  namespaceSelector:
    matchNames:
    - loki
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: querier
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http-metrics
      relabelings:
        - action: replace
          sourceLabels: [job]
          replacement: "loki/querier"
          targetLabel: job
        - action: replace
          replacement: "homelab-live"
          targetLabel: cluster
      scheme: http
