apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:GB5Kk8hwjZ9rYCHOvjOKiA==,iv:MAIUqtmIi3jfPRnhsFacu7Uh9xPNkEnFfcp8tK5DOE4=,tag:7fcl91jqnzVsjBxjaHmDrg==,type:str]
    secret-key: ENC[AES256_GCM,data:LmR4OwgP1aWhmOauuT3/phs38mcFIHOqB8ZF+n7NXw==,iv:B8cewhEErdgNxBLI1vIorCiIR0n5ONOHeAzvYt6JvqM=,tag:/q47QUoLhx/igO0yaIrNvg==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T01:52:02Z"
    mac: ENC[AES256_GCM,data:hOTXNa1HGAulPiBgxlLFCAdCsO5K7X09cfmJe2Rkpph8D+sPkwM5ygd009Up+AcwWK7SY1zHiYsl7WMltK2gUsrLEaP2cAC4SRrIPkWvaxjLB8rQMQf4+Vw3l9Qjcs/h7vW4MxIRC6zp5Wo4ydmkuW1ePr3HONcf6B1xzS+gH7Q=,iv:pKUGR3u00DEhGYtggzhZZMjEAshynceFd630hJfkPGA=,tag:GXQXbVXdRNsgXtaQYaZSmg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
