apiVersion: v1
kind: Secret
metadata:
    name: convertx-env
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:nQuKwRamwT7WItLezwuSAbwdt69zPAjCfgp9zdsMGdEYnP0lfj+H8aO9yNyPX6VyAHMvkJwTTbB2UqxqCWke7w==,iv:3IRpd38wzWc/TpZBYAA7YpUT+Nby65hIdlAcUQ+N8Dw=,tag:raVdmdMLSOdlFTSjd7iR1A==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eFVObE5WbEFlcDhoMTdE
            UG52Ri9RL2ZXN2M4VDN3NGlINU5aMjBNcEU4CkJOVUUzcUZrTU9xaDZTeVJneDlu
            dVZ3Q2N3dnd3cW93akJIVVAxdFhZejgKLS0tIGpDSzh6SHZIM1B3bUh0WDhYdVNH
            aXdXajRoNDNrTk8wUTJDRXdTb2JPa2cKI46SlSl0xlGaiUZlNstFKCbbRcq6QQzC
            ce2bLdyV+5lSSPlzkZw9RshR6lXVfjZFfkdBzhv34sB/arO2gNt3Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T17:08:23Z"
    mac: ENC[AES256_GCM,data:350KDD5HT48uLjlUw+HuS26nJBfz1nNcNx1vx2KzuzWQQtSFH814sjlELqWsAsvD2rmtXCMrVx6dZ0qLFSNzVxdBZhz5LNdn0hJqgshyTPhTWTsErPtbOUibik1NT50DFImqwHYO1ae3CXpaldDtcs4KCYKUgpNqVqXJ+NtHS4c=,iv:JeKw7RtoAcfE25rAJxYTk+JfQwQetUDAJ2qePQ1BTHk=,tag:4ErMpS03idOIbrl/8Bsy/A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.2
