apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: shiori-data
  name: shiori-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
