apiVersion: v1
kind: Secret
metadata:
    name: shiori-env-secret
type: Opaque
stringData:
    SHIORI_HTTP_SECRET_KEY: ENC[AES256_GCM,data:b9b4ASXJmC765O17RIAuac3nmuaed0MMQNCVX+xoIdhjgca2I2c=,iv:MTZxgKfCLlcnyxuAqNdlGB8Barw+2y2uhkSD1dM7mjo=,tag:2p1y32jrUczN+0l1Yj8/+Q==,type:str]
sops:
    age:
        - recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkczVDN3UrUjdOUmxwZEVQ
            TGRBbGoxWEdlZ3JWZC9KZ1BRMmNhVHl5QlZRCmk3OTJyNVNhVmdmNjhyT2V6VTlS
            ZDROMmJZSVpMOWZsWnlibCtsNlEyTVUKLS0tIDlHeFh4aWJvckdkQVdVVVdYZjh5
            SW16bUd6VHQ2MWJPeGZQMEo2bFdCQVkK5kKHFBr29AtN6ZUSTrwguAyb8F2qm2ZV
            0e0qEcS/3BPJlaw2YQ2upjeOi3CdIwqmrxERcClSu/cE+FouRcTITA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T01:23:12Z"
    mac: ENC[AES256_GCM,data:FV+rU8Dpe/zEL7rL63kcnlYu40xRHWu/xXb1nbzhWyAhyAlJx1v/t9i4bMm9bRqMhnVvhr9kHXglNHzLBOu5vWu4aSpCVoXajRtKp81q/mGFcBzy4pRA0MJTTYBJ88Re7kOwMz0euqgwFo0rxoEibj6UWa69Xzn3oM6TFMac29A=,iv:LSrC9PU8rJs+X4uP7kIcRjbVhiijmNoBjXWPJZeVmCw=,tag:xGZuDKiIxWUexRaZEXFSzQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
