apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
        - name: intel-gpu-plugin
          args:
            - -shared-dev-num=10
            - -enable-monitoring
            - -v=2
