apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo-backend-scheduler
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: backend-scheduler
    app.kubernetes.io/part-of: memberlist
spec:
  namespaceSelector:
    matchNames:
    - tempo
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: backend-scheduler
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http-metrics
      relabelings:
        - action: replace
          sourceLabels: [job]
          replacement: "tempo/backend-scheduler"
          targetLabel: job
        - action: replace
          replacement: "homelab-live"
          targetLabel: cluster
      scheme: http

