resources:
  # renovate: datasource=github-releases depName=cert-manager/cert-manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.21.0/cert-manager.yaml
  # - servicemonitor.yaml
  - grafanafolder.yaml
  - grafanadashboard.yaml
  - externalsecret.yaml
  - selfsigned-issuer.yaml
# patches:
# - patch: |-
#     $patch: delete
#     apiVersion: v1
#     kind: Namespace
#     metadata:
#       name: cert-manager
# - target:
#     kind: MutatingWebhookConfiguration
#     name: cert-manager-webhook
#   patch: |-
#     - op: replace
#       path: /metadata/annotations/cert-manager.io~1inject-ca-from-secret
#       value: operators/cert-manager-webhook-ca
# - target:
#     kind: ValidatingWebhookConfiguration
#     name: cert-manager-webhook
#   patch: |-
#     - op: replace
#       path: /metadata/annotations/cert-manager.io~1inject-ca-from-secret
#       value: operators/cert-manager-webhook-ca
