namespace: strimzi-cluster-operator-system
resources:
- namespace.yaml
  # renovate: datasource=github-releases depName=strimzi/strimzi-kafka-operator
- https://github.com/strimzi/strimzi-kafka-operator/releases/download/1.2.0/strimzi-cluster-operator-1.2.0.yaml
- networkpolicy.yaml
- clusterrolebinding.yaml
- podmonitor.yaml
- dashboards
- kube-state-metrics

patches:
  - path: patches/cluster_role_binding.yaml
  - path: patches/deployment.yaml
  - path: patches/role_binding.yaml
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: STRIMZI_NAMESPACE
          value: "mimir,tempo,kafka"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: strimzi-cluster-operator
