apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/instance: mimir-store-gateway
    app.kubernetes.io/name: mimir-store-gateway
    app.kubernetes.io/part-of: mimir
  name: mimir-store-gateway
