apiVersion: v1
kind: Secret
metadata:
    name: backstage-env-secret
type: Opaque
stringData:
    BASE_URL: ENC[AES256_GCM,data:a4cBFvrDzN4dIGSafl7lKhWl7lzD5N/F6xg+MGkTZg==,iv:pB9BBFU+83Ru/zwHjch551NIpj442K8FH1UzKCPOLGQ=,tag:TiZUx8W9Yk3K+7Cwf9F0gA==,type:str]
    ORG_NAME: ENC[AES256_GCM,data:0YQY6AxT/lnAXlCPj0swzcf/5E3ZybM=,iv:n2dyN7vQhO2oo2Cm7funlG+Hhs2Xp0inbg7oXOyHor8=,tag:vrz4kmbXSwVcCSL6kOkRnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aEVKQ1IwMXlmNjd6cVdU
            RWY1TnhENnZaWkdRMmt3cDRSbkIxNVlvWmtZCnZzQXVZR0gxMDFQaXNBaHZheVhF
            WEZFR1Y4eUMyMi85SDhkckVTN0Y5bmsKLS0tIFFJeGFBZHVhY2h3YVlOWjN4b29F
            WHlIVGtKV0dWSXE0SEd1Q3paZnY0amsK1C+ARiRC0yWOscbBEZufefllsdK09fqn
            OXiOGdjSMqgVmlO/162QbRkXj1p3NFUJjIZxd2pnJimcU3s8vo0uPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-05-31T20:32:11Z"
    mac: ENC[AES256_GCM,data:rYJAqOWN2XYsQ0KwIkiEITZ+lpIwMFyzdavG+KH/aiHGPs5NbS9Hw0Y/iYPk5kLv1i+uW6oGvG2uSnIe08quD+nAyku7GwN/bbVska/+oAAoqhOwKJ6sIweR4nshHh1AwGDasRlEw2c164TnJTPmSECwT+ZEiv68MDmmb+2niz8=,iv:hrQD5NC6S+DB6bGkJdbEUe+JJU6JfbEz6RDzDulE3Rk=,tag:fnK30EiIusWZojKbjnd2CQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
