apiVersion: v1
kind: Secret
metadata:
    name: nautobot-env-secret
type: Opaque
stringData:
    NAUTOBOT_SUPERUSER_EMAIL: ENC[AES256_GCM,data:XxOkW5CMuxEZNoXd7v0OwCee5A==,iv:BnkkmrfSswb1lxGyDqGaFGHMHeqLz4AilfvShKR+e34=,tag:ykL16pSNAi5rcNec2lyjbQ==,type:str]
    NAUTOBOT_SUPERUSER_NAME: ENC[AES256_GCM,data:HGE/6jA=,iv:r8sy2E2CaCdrdZG9TjF6YwBuwE9SGKh0U275hLE4e04=,tag:I38Ta5Tdx0fBydvJQ86EZw==,type:str]
    NAUTOBOT_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:u+eWF1UHb9ROPs73nmZlMUHfGy/OJOX7hQsti/UwQ7acXsLm,iv:U37DBiTGt1/GeOdK+pk45BTaMzJ52dJT9odI3F6cJpw=,tag:HN9lUw7WM/mvGV7hBL1zdA==,type:str]
    NAUTOBOT_SUPERUSER_API_TOKEN: ENC[AES256_GCM,data:kiyFUQAfeEN66aWu87Pr0415YOfp6MFuzbCKHI2BVElE90nNoYvfxw==,iv:C6lAHjBYtiVJnGL9Z26zS8IpWp5a26wkj7Gbif7pbM4=,tag:dl/dN1pJHEbuQxJu7aLRww==,type:str]
    NAUTOBOT_SECRET_KEY: ENC[AES256_GCM,data:MVoERODaxh5P0wpRjHDdvB/v+KVMheSCXNVlURzxbQkeO1NKc8Ad5FM8BaYOUL96SrISPXFo4R33MX573/QTpQ==,iv:lOWWn4JbLdDPs/Ww61PoxmpGRkkXogNPheLV1vrFdbk=,tag:sa5bQSDXc9tR22PUKqDDMA==,type:str]
    NAUTOBOT_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5fI9IGqra1G03uKIWK4s53c=,iv:H6r35T41+P0hR723JWKJRMscTLOZ+J9unlCTNw6jBiA=,tag:pDK5CDg4pmP67axC8YIJ/w==,type:str]
    NAUTOBOT_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:q2mJgjwg2W9XC+JSK+M7tCPPdpVIs7jroeQ=,iv:igC1crx93c4RcZRFAmlOA9Mm31whyZqay8Op/1Xz4jg=,tag:IVFJS2oXVQLADrMTge7F7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQnZLZnZvaysvV25JdWZo
            Tk4rS3FSZXZYNEJRcVBoNWljREhWNnc4QVRBCk01d0hWZVFRZ3krQW5FVGtYSjgy
            Q0lvMVprZGlldjRCTzVpTjlhSFdjZmsKLS0tIEY0aFRmMlA0MmxTcVhYKzBlYkR5
            N29Ka0QwZ1RPamg4Zmtpbk9ZaEtDMkkK7XTIO191fw8Cwr1aKFJtt1CEV5skPAQo
            Dd67Ie0UhvhAEtr4g9ExRgMW/Uxd1iDiKjBEuYF/FyNgW5a01Ox3wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-05-17T22:22:37Z"
    mac: ENC[AES256_GCM,data:f9mlCY2QpZqJLZSp9DSf24fKAJ+Gy2ZDwSWHfcBg98C/RjzrmsnOowsfPChFLo5qT6UJrJXUripH2sIUxYcKUMKQ0FK8FqvwN3+vs5mxt7D4yP86uZ+a9AEV8RnVT/duBEoAH0kyXJBepJEmWOURYikiQlsGkF/Yz/QufwtV+M0=,iv:V6jqu5IlzBXJ6oGDvfmi60fCNE4azg6ZCWtOpUVggbs=,tag:JiueyZzE7LkALlBPrGTZYg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
