apiVersion: v1
kind: ServiceAccount
metadata:
  name: nautobot
  labels:
    app.kubernetes.io/name: nautobot
    helm.sh/chart: nautobot-3.1.1
    app.kubernetes.io/instance: nautobot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "3.0"
automountServiceAccountToken: false
