apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:y6DyK1ZDQjSajOJT7yxOI1Qn,iv:PcAUi/Glpkb/JHGHmLMSTqgvQv7PyY3uiTWUBgYW8jA=,tag:agpd2Fh7LD/TN9xi/9X2ww==,type:str]
    secret-key: ENC[AES256_GCM,data:F6MfKTIXZtobm4lyGErV3A==,iv:4vjx+kDig62cUqjYp9Dqogfb+KCNqa4XaLHmp7Mh84M=,tag:Y+oGEMJZoZawkqoRBEyjMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-05-17T19:29:25Z"
    mac: ENC[AES256_GCM,data:pFzgryd7xIPcGZKRtIbIMl51MrdjiHt8zVawXKZi2uDQuqbK9kJ7X47+uAo6sCpTmajwgUs+yhmavdZl7UzjtCcMcnsbFsoqmKxrnFxp3e5cnm4dwnaB6BE6Qmflkp0QuzwdmvRoDHJkz7lBAEsioJ/mGrMB21pe2GTliKWNST0=,iv:5lqNiRPKeSv/5zMggCkKA+U0NmjGaepYIjYx0Ghlo+Y=,tag:+i3GCV0mh+NF/xDB59Rs6Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
