apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: bentopdf-tcp-30s
spec:
  jobName: bentopdf-tcp-30s
  interval: 30s
  scrapeTimeout: 30s
  module: tcp_connect
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local.:19115
  targets:
    staticConfig:
      static:
        - bentopdf.bento-pdf.svc.cluster.local.:8080
