apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-creds
type: Opaque
stringData:
    access-id: ENC[AES256_GCM,data:hfy43I938nafKA2zu9srAIgW7g==,iv:LCjmXRNKOSY+DOdlyo3tRr/rM92CnKY4j6PXgZ7eVeA=,tag:WFAunZAJFYCjQn0eTeC/6Q==,type:str]
    secret-key: ENC[AES256_GCM,data:4E5iN29swdRqA9YxV29e5+eJBltbMnqZmIwUP/DN,iv:2F2CKBCWKlQRuuJd+zLam1WxmOopoxlrr9BL361pTKM=,tag:mZmGkMdp+kGr4oN6jHmcnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RGllUml6TUh0a1ZBR0Yw
            azhZK3Vic0JUaE1SNW1XWE5VQzFoSmsvTGwwCkZRNTZRTVl1aDErWkJsSHV0K245
            Y1N5eExJWjcrTU9mS1o4K3ZJNlNrcDAKLS0tIDZCOEl3aXRJMXE2cDZoZGlmS2Fn
            ektQckVKVi9hOXhDVjc0SldvQTg2ZHcKE6DVaJynh6DfWJIjMFHf4gj9kyElL7Tu
            eCGZBqJzWP1scCaDKWe9j/6fSTaZc8jJA9fWym5cREvys79XTjfWsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-05-29T22:26:09Z"
    mac: ENC[AES256_GCM,data:ek929EyBRAW3HDj2OLPvPSTinOU5V+02gzhOJPULBWTWIZSYehj+JQpvzrDXqoBW/EdrMQFUjqEAFOPyk8JFpLVlDD5cJLy1JxsXq0mgwG/mF/ER9RKL2QIii9vGF+xSVCshyZP3iKyRxAeEHHPd+/4dEt49HcdrwGP/1hQ2pgw=,iv:cHPpvUkSYOKS/9WwBWtPfJJhWPRcGQLtyJwMDFO/6WA=,tag:QXlE4yxGAf5OKmy8TA848w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
