apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
    name: tcp-static-urls-30s
spec:
    interval: ENC[AES256_GCM,data:q2B2,iv:2XNR+ATCBtpF9vTURppdKgexgFmkbYP3av1Os04GyGA=,tag:sBgk29m6D23VQR+7OjbrTw==,type:str]
    jobName: ENC[AES256_GCM,data:4vvmGREZVNdTLtt6k23l6TatV2hPx28xf7Q=,iv:+Rn+b7iW+CIGUvcH2V8vIyEd8aUmJx3wmB3KDVa/tO8=,tag:+czgiwznm7JAYZEc7gZZYA==,type:str]
    module: ENC[AES256_GCM,data:YzByk/GwPb7jPLA=,iv:PZSESLSJr3KoBmgvthvLyqcm5MvMVqkqmziiOD2Zwj0=,tag:VMaEDtVfjqVkh77BsbZe2w==,type:str]
    prober:
        path: ENC[AES256_GCM,data:DYCgx3f4,iv:EPCcTIcpFhS/DwkaavPGBZRzOYtQakQOq2hKEo65KAg=,tag:B8RunocLrXjSRl4Jf0Hy6w==,type:str]
        url: ENC[AES256_GCM,data:DKMD70W/bXLO8kcMoCLiHEgAyqbdgLeinsFc+wCvFDGqTTyJTraps0+9+HIqHdgml85wYfWu2pTaemkN,iv:GVlVUksUYCbgq8cqeIrJOK8VuUO6ot5PhFHvd3rhgtE=,tag:K/gGdQuOiNMIaGCy9gVbkQ==,type:str]
    scrapeTimeout: ENC[AES256_GCM,data:oFT9,iv:dhAIrUSgYR53+xP7aQ3o17FY5XhLJDlt9ziGwIqkjAI=,tag:/pgtmeeHMLW6o0/XHQ0faw==,type:str]
    targets:
        staticConfig:
            static:
                - ENC[AES256_GCM,data:d3rszma0Xk3w9DiHv0a44gUbJDJZ,iv:rvhunhuljVL858Tj+SoyAugP0cPn3NhrA+oWQqJyDHA=,tag:zckmgeB+czJUKImPMBcIMA==,type:str]
                - ENC[AES256_GCM,data:abJcjKGOEiiL6tJRBGyd6F8DJww=,iv:3SvCF/275g9juE1YgYZVgUaK5nVbUktRxJI3K85/rSI=,tag:VUn9gRQH+O5JhhirONPL0A==,type:str]
                - ENC[AES256_GCM,data:wQGQQCTFzFGqrpBDySjff1EXnYA=,iv:WVhGVFIwZbfHFejErgDYuJWdORnRHqfIjUXaeKepQ10=,tag:1Ode7X8L+cI2uVZlDjhLng==,type:str]
                - ENC[AES256_GCM,data:s6Vfv998xB4Q3ukPMFBh8AQjQVvK,iv:fxnrFrhi26mdSh9RuLeiSLBJXx4SNMyRUq/chNFDa44=,tag:WarhMIne1oe2ImAAURhmNQ==,type:str]
                - ENC[AES256_GCM,data:WzC5TBNK7d4Fo/YjT5LdSxip,iv:bfFmXFvfcIjMrU8WcQ0ub6cnNRl3Ha6oRnXbdvKgkTE=,tag:k8R6ny0ksHtcCcgm8gZizw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWxEUUdrRFNtaVZKUFY1
            WlBxcCs5ck95VWJVaGIvdHRkUkphbmlGMmpvCm1rajFTWWxjQkxOTG9RLzV0eFBv
            SGE1RXdRclNnZHVjQ0NRZVlNT1kvRUkKLS0tIHZ6OXJicnRQeTN3a1htcGZHVldM
            SlcvV2tIV3RvTGFnZ05ZWjdpSjNqTG8K7xU+4iKSYeGQ/zvCrfR3i5fbAp6FIWoh
            Ur0FwhL2EQXvrtLS/xcMYbweSsN2Oqf4sq3AxBwrPcRK+pl6S5VijQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-07-08T19:30:01Z"
    mac: ENC[AES256_GCM,data:Vc8DMMJ2nAjv/Zr4bKpLmfz5RwbQEOxStl//0AjU/BZDseKgODUso1fgpIHn8BlA3eTPwfaaXhH2iECBHickc2jR3MPeumFesiLDInGhupSmNIbzQSYxerZt9B8pdPU3oUPKYmRbE6fqbf727Vt0o6UTh/hZMobHHYrwglRNAds=,iv:OXLn+zeuQrS9oxKmH2dnnoSvLzZNTTJWititR49CC84=,tag:uPpfNJ7+wnnGAPTNTiy7HA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
    name: http-cloudflare-tunnel-urls-60s
spec:
    interval: ENC[AES256_GCM,data:EiWH,iv:FNPiDpSYHSD21XNHxZj0as0fhx+aNB1t5zrJPucZQZY=,tag:jxh0fVFi6l3q2iuZAEmsMg==,type:str]
    jobName: ENC[AES256_GCM,data:KcoEPrmTBozA+dqtqc8tb6V8d2ekdKLj8jWxw9w+Nw==,iv:i9G3fFCG4HZTUz1XQPwkjw/J4k9QxtaEiv+ae7YojxA=,tag:zfQ5au3hx3RD4A7ylmjdyA==,type:str]
    module: ENC[AES256_GCM,data:V4kGo7p3805ipb9QGx/6jnIINQlAJ86jgBo=,iv:u29f2v48aKglXgqxChK9qSbV/Qoyj3a+ga6SzbAAOyg=,tag:ryyJqTEs0X8Cpr9JjEOwRQ==,type:str]
    prober:
        path: ENC[AES256_GCM,data:MgAv1iOz,iv:SKUHnmdsKoSbfUb64idEMaPcM5BHeq06GHLQI4hBILc=,tag:5zSJI1RBKSl/26r0kamvDw==,type:str]
        url: ENC[AES256_GCM,data:uKsbtsfVs90kX906PAKkkXyOUWm0tbhONrfSK5iJ4Xfexjk273gkoewGBJHvZl07diIRSRHDucsith9v,iv:7KvuWKqjmBAKiGxFz8uA7qCxz3C7bx+GoQd1NTy+iwU=,tag:HyIbc++lgbscP+e2JzLrXw==,type:str]
    scrapeTimeout: ENC[AES256_GCM,data:EFQ1,iv:6aTln+I/tzhhq5zs8nhgVwEBUWE0BlgeOVceb+58rhA=,tag:15o4TPIZftCwKLTMFheqIA==,type:str]
    targets:
        staticConfig:
            static:
                - ENC[AES256_GCM,data:+t5Sfe1+QUwxIbM062x/uqg=,iv:lE33vOc07dA84fr5AONpMGeR1c18adCwiF1XoE4DeLQ=,tag:nBHDbX273YVDqu10ad3W8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWxEUUdrRFNtaVZKUFY1
            WlBxcCs5ck95VWJVaGIvdHRkUkphbmlGMmpvCm1rajFTWWxjQkxOTG9RLzV0eFBv
            SGE1RXdRclNnZHVjQ0NRZVlNT1kvRUkKLS0tIHZ6OXJicnRQeTN3a1htcGZHVldM
            SlcvV2tIV3RvTGFnZ05ZWjdpSjNqTG8K7xU+4iKSYeGQ/zvCrfR3i5fbAp6FIWoh
            Ur0FwhL2EQXvrtLS/xcMYbweSsN2Oqf4sq3AxBwrPcRK+pl6S5VijQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-07-08T19:30:01Z"
    mac: ENC[AES256_GCM,data:Vc8DMMJ2nAjv/Zr4bKpLmfz5RwbQEOxStl//0AjU/BZDseKgODUso1fgpIHn8BlA3eTPwfaaXhH2iECBHickc2jR3MPeumFesiLDInGhupSmNIbzQSYxerZt9B8pdPU3oUPKYmRbE6fqbf727Vt0o6UTh/hZMobHHYrwglRNAds=,iv:OXLn+zeuQrS9oxKmH2dnnoSvLzZNTTJWititR49CC84=,tag:uPpfNJ7+wnnGAPTNTiy7HA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
    name: http-get-static-urls-60s
spec:
    interval: ENC[AES256_GCM,data:PHKl,iv:awG4EWSY98zhdng7CMhCdPc/f7Y1bmSk0ekIUn4M6w4=,tag:f8Q1qT2PJ453L/NCNmVjEg==,type:str]
    jobName: ENC[AES256_GCM,data:aNvy4GhQnsVlHS4NX39Sen3D4TJFBHB5,iv:ho174PEDB6JOu3AmmayP0CndxL69SZ732Ea8Ph2OdfM=,tag:+grJlatqL6PVGxbhj6Vdjg==,type:str]
    module: ENC[AES256_GCM,data:tjx3Sfp1jhRaWYXl,iv:mdfk9nqRjtrN5olI2oxV9RmxmBmqDbLk0AxhFw5FmiM=,tag:IlF3sZK++lMRlxG7ztnyrA==,type:str]
    prober:
        path: ENC[AES256_GCM,data:QXui7pM3,iv:UKAYmciuGUl9cYHBGufDqNC2gBPXDe+2bQzEWuSlA6I=,tag:STpSZXW96TIuRbi1DKxN9w==,type:str]
        url: ENC[AES256_GCM,data:ApbSfCRq0Tlf8yEk97zvBnewTewo0jflBEk3lWq3WETd5OkSjoBP5cCzrJYoKj4G65IF69qOei7YbEN3,iv:59iJVhuZd+KXkZ671vXwMD7G/OkqarI4P4OiJ8zm6Lk=,tag:xJchx6AgF7LUxa2XpVvaaw==,type:str]
    scrapeTimeout: ENC[AES256_GCM,data:Ug/Y,iv:qFnGUYXZccpd9eaKJda0lMviBU+TomrW47QMgPFWLrY=,tag:mNFG7ltr9oAfzQsYVS+M9g==,type:str]
    targets:
        staticConfig:
            static:
                - ENC[AES256_GCM,data:Ptq8EjpmThokID6JUpkGz5iJumEY3o7wfw/+h1xJ++ZgwQ==,iv:+cbWnW5a6d+YkAXzXe6pDy3ie+ltoPdZ1gsyAF9vVdQ=,tag:J8/hNIKWHkeWFCEedtXkZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWxEUUdrRFNtaVZKUFY1
            WlBxcCs5ck95VWJVaGIvdHRkUkphbmlGMmpvCm1rajFTWWxjQkxOTG9RLzV0eFBv
            SGE1RXdRclNnZHVjQ0NRZVlNT1kvRUkKLS0tIHZ6OXJicnRQeTN3a1htcGZHVldM
            SlcvV2tIV3RvTGFnZ05ZWjdpSjNqTG8K7xU+4iKSYeGQ/zvCrfR3i5fbAp6FIWoh
            Ur0FwhL2EQXvrtLS/xcMYbweSsN2Oqf4sq3AxBwrPcRK+pl6S5VijQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-07-08T19:30:01Z"
    mac: ENC[AES256_GCM,data:Vc8DMMJ2nAjv/Zr4bKpLmfz5RwbQEOxStl//0AjU/BZDseKgODUso1fgpIHn8BlA3eTPwfaaXhH2iECBHickc2jR3MPeumFesiLDInGhupSmNIbzQSYxerZt9B8pdPU3oUPKYmRbE6fqbf727Vt0o6UTh/hZMobHHYrwglRNAds=,iv:OXLn+zeuQrS9oxKmH2dnnoSvLzZNTTJWititR49CC84=,tag:uPpfNJ7+wnnGAPTNTiy7HA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
    name: ssh-banner-check-60s
spec:
    interval: ENC[AES256_GCM,data:K1aj,iv:w+2JSkStfHxsUbW+5WV1zNL4RaGnwcTSnbSJupdrp/Y=,tag:BIHI2YmPXlC0yn6cmHXiJQ==,type:str]
    jobName: ENC[AES256_GCM,data:02w1WVnotdDDFNiqHoUCcC0Pxn0=,iv:Hael4QF/pONS16espfZchhu4oeUMRuRaNLhSH0b5yi4=,tag:N94P7+fYG89X7bj1utd0nw==,type:str]
    module: ENC[AES256_GCM,data:+XteQx42izlPDw==,iv:zWSyT/NE5nm56Zkx6w7FPf5E8QrH9JXRRnlhOW3fp/o=,tag:KxoorjSuANFAbEYFEB1jMg==,type:str]
    prober:
        path: ENC[AES256_GCM,data:LVI4LsyH,iv:seYA6iHRZmwKYfg6TrDXXB7Nz40efvTRcfOTeFTbqnU=,tag:9u2+YkKhdGM0HoDgdC4n5Q==,type:str]
        url: ENC[AES256_GCM,data:/TO9aa1F7YD4EsgEGTmkRoeCHyTFPh16oeaz13cuCymSOPoShdlZiBI9DooKyYGZcakbrbRC5vhaMh44,iv:DIrp8XsZPkJ1OAdfu0Mk3tE7XBJiJ4LiNlalYeUyxM0=,tag:Q5+NIYzujpB8zDYr0kj3LQ==,type:str]
    scrapeTimeout: ENC[AES256_GCM,data:t5kz,iv:MDo2v+BaUCNh5YhAlthHSW28QYg/r6byS3nBp9YzhGs=,tag:nXFLwmVqYxZtBlAywIrzxw==,type:str]
    targets:
        staticConfig:
            static:
                - ENC[AES256_GCM,data:ZfQmnCs8kna2tfccjiRavbqFiA==,iv:W518uJgG6w/42nIvHT5B0HqeCUV0OxZwMMHbC89dZHc=,tag:lUaHfgPTxgwHPlZnVCuifA==,type:str]
                - ENC[AES256_GCM,data:j1rTjSd2r9DmitMijf31fXgzkw==,iv:g32/OxzoDSOknaPUsM2PRX+O4bhNb8yqHofQhqv2lz0=,tag:JLDXXM2SIL2+pq88NnNLKw==,type:str]
                - ENC[AES256_GCM,data:BzNFH3kmMbD9FztrQJLWzw==,iv:uFuQrtD8bKCLrrz6klkGHEnsh5/qeOSe/dOumnPspeY=,tag:IjU2dP1vqs6nSug5uM8NJw==,type:str]
                - ENC[AES256_GCM,data:g5JG3FkNzknMt657JN61Pw==,iv:juyl9h1cB7tBfRsbPSr83A20FBSmj5oHFZZSsY2Nx3s=,tag:JUOtZW6OFJBkrlnGyQEFpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWxEUUdrRFNtaVZKUFY1
            WlBxcCs5ck95VWJVaGIvdHRkUkphbmlGMmpvCm1rajFTWWxjQkxOTG9RLzV0eFBv
            SGE1RXdRclNnZHVjQ0NRZVlNT1kvRUkKLS0tIHZ6OXJicnRQeTN3a1htcGZHVldM
            SlcvV2tIV3RvTGFnZ05ZWjdpSjNqTG8K7xU+4iKSYeGQ/zvCrfR3i5fbAp6FIWoh
            Ur0FwhL2EQXvrtLS/xcMYbweSsN2Oqf4sq3AxBwrPcRK+pl6S5VijQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15x8mqr8j40rtzeg98wa536jt85276crszk7qcrprndveq4049esq6padka
    lastmodified: "2026-07-08T19:30:01Z"
    mac: ENC[AES256_GCM,data:Vc8DMMJ2nAjv/Zr4bKpLmfz5RwbQEOxStl//0AjU/BZDseKgODUso1fgpIHn8BlA3eTPwfaaXhH2iECBHickc2jR3MPeumFesiLDInGhupSmNIbzQSYxerZt9B8pdPU3oUPKYmRbE6fqbf727Vt0o6UTh/hZMobHHYrwglRNAds=,iv:OXLn+zeuQrS9oxKmH2dnnoSvLzZNTTJWititR49CC84=,tag:uPpfNJ7+wnnGAPTNTiy7HA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.2
